
import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { landingCa } from '../lib/i18n/landingCa';
import { landingEs } from '../lib/i18n/landingEs';
import { landingEn } from '../lib/i18n/landingEn';
import { portalCa } from '../lib/i18n/portalCa';

type Language = 'es' | 'en' | 'ca';
type Theme = 'light' | 'dark';

interface SettingsContextType {
  lang: Language;
  theme: Theme;
  setLang: (lang: Language) => void;
  toggleTheme: () => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  es: {
    "nav.home": "Inicio",
    "nav.login": "Iniciar Sesión",
    "nav.register": "Unirse Ahora",
    "nav.logout": "Salir",
    "nav.continue": "Continuar Formación",
    "hero.tag": "REDESCOMERCIALES.AI",
    "hero.title": "Convierte tu red de partners en un canal de ventas activo y escalable",
    "hero.subtitle": "Activamos tu red comercial indirecta para generar oportunidades con visibilidad del pipeline.",
    "hero.bullet1": "Más ventas sin ampliar equipo interno",
    "hero.bullet2": "Partners activos y alineados",
    "hero.bullet3": "Control total del rendimiento",
    "hero.cta.primary": "Solicitar diagnóstico de red comercial",
    "hero.cta.secondary": "Ver cómo funciona",
    "problem.headline": "Tu red comercial existe… pero no está activada",
    "problem.copy": "Muchas empresas B2B tienen partners o colaboradores, pero sin activación continua ni visibilidad del pipeline indirecto. La estrategia está definida; la ejecución en la red, no.",
    "problem.remate": "Resultado: oportunidades que no llegan a materializarse.",
    "problem.passive.title": "Red Pasiva (Actual)",
    "problem.passive.item1.title": "El Partner 'Fantasma'",
    "problem.passive.item1.desc": "Caso habitual: un partner registrado hace meses, sin actividad ni seguimiento desde el onboarding.",
    "problem.passive.item2.title": "La 'Caja Negra'",
    "problem.passive.item2.desc": "Sabes que tienen clientes, pero no tienes visibilidad de su pipeline hasta que la venta se pierde.",
    "problem.passive.item3.title": "Falta de Foco",
    "problem.passive.item3.desc": "Tu partner prioriza otros productos porque no entiende tu valor o no sabe cómo venderlo.",
    "problem.active.title": "Red Activa (Con nosotros)",
    "problem.active.item1.title": "Activación Proactiva",
    "problem.active.item1.desc": "Seguimiento y activación continuos para que los partners reporten oportunidades de forma regular y trazable.",
    "problem.active.item2.title": "Visibilidad del pipeline",
    "problem.active.item2.desc": "Centralizas la actividad de la red y el estado de cada oportunidad, sin depender de actualizaciones manuales dispersas.",
    "problem.active.item3.title": "Ejecución acompañada",
    "problem.active.item3.desc": "Operación experta que mantiene la activación y el seguimiento de la red, para que las oportunidades avancen con proceso y continuidad.",
    "solution.headline": "Un sistema para activar y gestionar tu red comercial",
    "solution.copy": "Metodología, tecnología y operación experta para que tu canal indirecto genere oportunidades con seguimiento sistemático.",
    "methodology.headline": "Cuatro fases para activar y gestionar tu red",
    "methodology.step1.title": "Fase 1 – Diagnóstico estratégico",
    "methodology.step1.desc": "Analizamos tu red actual, potencial y gaps de activación.",
    "methodology.step2.title": "Fase 2 – Adaptación tecnológica",
    "methodology.step2.desc": "Implementamos una plataforma adaptada a tu red: tracking de actividad, incentivos y gestión de leads.",
    "methodology.step3.title": "Fase 3 – Captación de colaboradores",
    "methodology.step3.desc": "Diseñamos campañas para atraer nuevos partners cualificados.",
    "methodology.step4.title": "Fase 4 – Gestión y activación continua",
    "methodology.step4.desc": "Operamos la red con seguimiento, incentivación y optimización continuos para mantener la ejecución del canal.",
    "benefits.headline": "Lo que cambia cuando la red se gestiona de forma sistemática",
    "benefits.item1.title": "Más pipeline sin ampliar plantilla",
    "benefits.item1.desc": "Genera oportunidades a través del canal indirecto sin los costes fijos de una gran fuerza de ventas interna.",
    "benefits.item2.title": "Partners con actividad real",
    "benefits.item2.desc": "Pasa de colaboradores inactivos a una red con activación, incentivos y seguimiento continuos.",
    "benefits.item3.title": "Visibilidad del canal indirecto",
    "benefits.item3.desc": "Centraliza la actividad y el pipeline de tu red para tomar decisiones con mejor información.",
    "benefits.item4.title": "Red escalable y medible",
    "benefits.item4.desc": "Procesos homogéneos que permiten crecer el canal manteniendo control y calidad en cada incorporación.",
    "benefits.item5.title": "Modelo alineado a resultados",
    "benefits.item5.desc": "Inversión inicial, gestión continuada y componente variable según el desempeño del canal indirecto.",
    "diff.headline": "Por qué esto no es una agencia ni un software más",
    "diff.agencies.title": "Agencias",
    "diff.agencies.desc": "Generan leads pero no activan redes",
    "diff.saas.title": "SaaS",
    "diff.saas.desc": "Te dan herramientas, pero no ejecución",
    "diff.us.title": "Redescomerciales.ai",
    "diff.us.desc": "Sistema completo: estrategia + tecnología + operación",
    "cases.headline": "Diseñado para empresas que quieren escalar sin aumentar costes fijos",
    "cases.metric1.val": "Activación",
    "cases.metric1.label": "Sistemática de partners y colaboradores",
    "cases.metric2.val": "Visibilidad",
    "cases.metric2.label": "Del pipeline indirecto",
    "cases.metric3.val": "Oportunidades",
    "cases.metric3.label": "Generadas desde la red comercial",
    "model.headline": "Un modelo alineado a resultados",
    "model.copy": "Trabajamos con un modelo híbrido: setup inicial, fee mensual de gestión y variable sobre resultados.",
    "model.remate": "Ganamos cuando tú vendes.",
    "whatIs.title": "¿Qué es Redescomerciales.ai?",
    "whatIs.text": "Redescomerciales.ai ayuda a empresas B2B a activar y gestionar su red comercial indirecta. Combinamos diagnóstico, seguimiento, metodología y tecnología para generar oportunidades con visibilidad del pipeline y una lectura más clara del impacto del canal.",
    "trust.label": "Sectores con los que trabajamos",
    "trust.sector1": "SaaS B2B",
    "trust.sector2": "Consultoría",
    "trust.sector3": "Servicios profesionales",
    "trust.sector4": "Fondos de inversión",
    "trust.sector5": "Scale-ups",
    "faq.title": "Despejando dudas",
    "faq.q1": "¿Necesito tener ya una red?",
    "faq.a1": "No es imprescindible. Muchas empresas tienen contactos infrautilizados y otras parten de cero. En ambos casos diseñamos la estructura, los incentivos y el sistema de seguimiento para activar o construir la red comercial.",
    "faq.q2": "¿Cuánto tarda en verse resultados?",
    "faq.a2": "Los primeros indicadores de activación suelen aparecer en semanas. El impacto comercial sostenido se consolida en meses, según el tamaño de la red, el sector y el nivel de implicación interna.",
    "faq.q3": "¿Qué tipo de empresas encajan?",
    "faq.a3": "Empresas B2B con ciclo comercial estructurado: SaaS, consultoría, servicios profesionales, fondos de inversión y scale-ups que quieren escalar ventas indirectas sin ampliar costes fijos.",
    "faq.q4": "¿Qué implica para mi equipo internamente?",
    "faq.a4": "Poca dedicación operativa. Activamos la red, hacemos el seguimiento y tú validas oportunidades. La plataforma centraliza la visibilidad del canal indirecto.",
    "faq.q5": "¿Por qué no basta con nuestro CRM o las herramientas actuales?",
    "faq.a5": "Un CRM almacena información, pero no activa ni opera la red. Añadimos el modelo de activación, el seguimiento sistemático y la visibilidad del pipeline indirecto que normalmente no cubren tus herramientas.",
    "faq.q6": "¿Cómo puedo solicitar un diagnóstico?",
    "faq.a6": "Desde contacto, cuéntanos tu situación. Te respondemos en 24 h laborables, revisamos tu red y, si encaja, agendamos una sesión de diagnóstico para proponerte un plan de activación.",
    "faq.q7": "¿Trabajáis solo en España?",
    "faq.a7": "Nuestra sede está en Barcelona y trabajamos principalmente con empresas en España y Europa. El modelo es aplicable a cualquier empresa B2B con red comercial o potencial de crearla.",
    "faq.q8": "¿Es un CRM, una consultoría o una plataforma de partners?",
    "faq.a8": "Es un sistema que combina metodología, tecnología y operación para activar y seguir tu red indirecta. La plataforma da visibilidad; el equipo ejecuta el modelo.",
    "faq.q9": "¿Cómo se mide el resultado?",
    "faq.a9": "Con indicadores de activación de la red, actividad de partners y evolución del pipeline indirecto. El seguimiento queda centralizado para revisar qué funciona y tomar decisiones.",
    "faq.q10": "¿Encaja con las herramientas que ya utilizamos?",
    "faq.a10": "No sustituye necesariamente tu CRM ni tus sistemas internos. Complementa lo que ya tienes centralizando la activación y el seguimiento del canal indirecto.",
    "contact.faqLink": "Ver todas las preguntas frecuentes",
    "breadcrumb.home": "Inicio",
    "cta.final.title": "¿Tu red comercial puede generar más oportunidades?",
    "cta.final.subtitle": "En una sesión revisamos tu red, identificamos gaps de activación y te mostramos cómo obtener más visibilidad del pipeline indirecto.",
    "cta.final.btn": "Solicitar diagnóstico de red comercial",
    "support.marketing": "Soporte Marketing",
    "support.subject": "Asunto",
    "support.inquiry": "Consulta a realizar",
    "support.placeholder_subject": "¿En qué podemos ayudarte?",
    "support.placeholder_inquiry": "Describe detalladamente tu necesidad de marketing...",
    "support.send": "Enviar Consulta",
    "support.success": "Consulta enviada correctamente. Nuestro equipo contactará contigo pronto.",
    "login.title": "Bienvenido de nuevo",
    "login.subtitle": "Accede de tu panel de gestión y continúa tu formación en el ecosistema.",
    "login.email": "Correo Electrónico",
    "login.email_placeholder": "tu@email.com",
    "login.password": "Contraseña",
    "login.pass_placeholder": "••••••••",
    "login.btn": "Entrar al Portal",
    "login.forgot": "¿Has olvidado tu contraseña?",
    "login.new": "¿Nuevo aquí?",
    "login.register_link": "Crear cuenta profesional",
    "login.recovery_title": "Recuperar cuenta",
    "login.recovery_subtitle": "Te enviaremos un enlace de recuperación",
    "login.back": "Volver",
    "login.recovery_success": "Correo enviado correctamente",
    "login.recovery_error_email": "Introduce tu correo electrónico",
    "register.title": "Crea tu cuenta",
    "register.subtitle": "Únete a la plataforma líder en activación de canales B2B.",
    "register.name": "Nombre Completo",
    "register.name_placeholder": "Tu nombre",
    "register.email": "Email",
    "register.email_placeholder": "tu@email.com",
    "register.phone": "Teléfono",
    "register.phone_placeholder": "600 000 000",
    "register.level": "Nivel deseado",
    "register.pass": "Contraseña",
    "register.pass_placeholder": "••••••••",
    "register.pass_confirm": "Repetir contraseña",
    "register.btn": "Crear cuenta profesional",
    "register.existing": "¿Ya tienes cuenta?",
    "register.login_link": "IDENTIFÍCATE AQUÍ",
    "register.email_sent_title": "¡REVISA TU CORREO!",
    "register.email_sent_desc": "Hemos enviado un enlace de confirmación a",
    "register.role.1": "1 - Ejemplos de venta",
    "register.role.2": "2 - Colaborador",
    "register.role.3": "3 - Delegado (Gestión)",
    "register.role.4": "4 - Delegado (Oficina Técnica)",
    "portal.title": "Panel de Carrera",
    "portal.subtitle": "Sigue tu itinerario profesional.",
    "footer.rights": "Redescomerciales.ai - Todos los derechos reservados.",
    "ecosystem.title": "Nuestro Ecosistema",
    "ecosystem.subtitle": "Cuatro niveles de colaboración adaptados para tu perfil.",
    "role.1.title": "Ejemplos de venta",
    "role.1.desc": "Recomienda nuestra plataforma a tu red de contactos y obtén beneficios pasivos por cada éxito.",
    "role.1.subtitle": "Ideal para profesionales senior con una buena red de contactos que quieren generar ingresos extra sin carga operativa.",
    "role.1.perfil_title": "PERFIL IDEAL",
    "role.1.perfil_desc": "Persona que quiera monetizar sus contactos. Consultores o profesionales de cualquier sector.",
    "role.1.economico_title": "MODELO ECONÓMICO",
    "role.1.economico_desc": "Sin coste de entrada (0€). Comisionas un 7,5% sobre el cierre de cada convenio.",
    "role.1.funciones_title": "TUS FUNCIONES PRINCIPALES",
    "role.1.f1": "Identificar contactos.",
    "role.1.f2": "Presentar la oportunidad.",
    "role.1.f3": "Nuestro equipo cierra la venta.",
    "role.1.ejemplo_title": "Ejemplo Real",
    "role.1.ejemplo_desc": "\"Caso Jorge (55 años): Consultor que monetiza su antigua agenda refiriendo empresas a nuestra plataforma sin involucrarse en la gestión.\"",
    "role.2.title": "Colaborador",
    "role.2.desc": "Gestiona tu propia cartera de clientes y lidera el proceso comercial con nuestra tecnología.",
    "role.2.subtitle": "Ideal para consultores y comerciales que quieren liderar el proceso de venta con tecnología propia.",
    "role.2.perfil_title": "PERFIL IDEAL",
    "role.2.perfil_desc": "Comercial multicartera, asesor o agencia de marketing con cartera de clientes activa.",
    "role.2.economico_title": "MODELO ECONÓMICO",
    "role.2.economico_desc": "Canon anual de 3.000€. Comisión del 15% sobre honorarios netos.",
    "role.2.funciones_title": "TUS FUNCIONES PRINCIPALES",
    "role.2.f1": "Identificar leads cualificados.",
    "role.2.f2": "Realizar el discovery inicial.",
    "role.2.f3": "Cerrar convenios comerciales.",
    "role.2.ejemplo_title": "Ejemplo Real",
    "role.2.ejemplo_desc": "\"Caso Elena: Agencia de seguros que ofrece nuestros servicios como valor añadido a sus clientes pyme.\"",
    "role.3.title": "Delegado",
    "role.3.sub": "GESTIÓN",
    "role.3.desc": "Lidera una zona geográfica y coordina redes de Ejemplos de venta bajo nuestro modelo de franquicia.",
    "role.3.subtitle": "Lidera una zona geográfica exclusiva y coordina redes de Ejemplos de venta bajo nuestro modelo.",
    "role.3.perfil_title": "PERFIL IDEAL",
    "role.3.perfil_desc": "Emprendedor o ex-directivo con capacidad de gestión y liderazgo de equipos comerciales.",
    "role.3.economico_title": "MODELO ECONÓMICO",
    "role.3.economico_desc": "Canon de 12.000€/año. Comisión del 30% y control territorial.",
    "role.3.funciones_title": "TUS FUNCIONES PRINCIPALES",
    "role.3.f1": "Reclutar y formar Ejemplos de venta.",
    "role.3.f2": "Gestión estratégica territorial.",
    "role.3.f3": "Representación oficial de la marca.",
    "role.3.ejemplo_title": "Ejemplo Real",
    "role.3.ejemplo_desc": "\"Caso Manuel: Ex-director de banca que gestiona la provincia de Valencia con una red de 50 prescriptores.\"",
    "role.4.title": "Delegado",
    "role.4.sub": "OFICINA TÈCNICA",
    "role.4.desc": "El nivel más avanzado. Gestión comercial total y redacción de expedientes con IA de última generación.",
    "role.4.subtitle": "El nivel de control total. Gestión comercial y redacción técnica asistida por IA.",
    "role.4.perfil_title": "PERFIL IDEAL",
    "role.4.perfil_desc": "Consultoras establecidas o expertos en I+D que buscan maximizar rentabilidad.",
    "role.4.economico_title": "MODELO ECONÓMICO",
    "role.4.economico_desc": "Modelo de oficina técnica. Máxima comisión (hasta 40%) por control total.",
    "role.4.funciones_title": "TUS FUNCIONES PRINCIPALES",
    "role.4.f1": "Redacción técnica con IA propia.",
    "role.4.f2": "Validación técnica de expedientes.",
    "role.4.f3": "Gestión comercial premium.",
    "role.4.ejemplo_title": "Ejemplo Real",
    "role.4.ejemplo_desc": "\"Caso TechConsult: Consultoría que ha multiplicado por 10 su producción usando nuestra tecnología.\"",
    "portal.btn.info": "Saber más",
    "matcher.title": "Matcher de Carrera IA",
    "matcher.desc": "¿No sabes qué nivel elegir? Cuéntale a nuestra IA tu experiencia y te dirá cuál es tu rol ideal.",
    "matcher.btn": "Probar Matcher IA",
    "matcher.modal.title": "Asistente de Carrera",
    "matcher.modal.placeholder": "Ej: Soy comercial con 10 años de experiencia en banca y tengo muchos contactos en el sector industrial...",
    "matcher.modal.loading": "Analizando tu perfil...",
    "matcher.modal.btn": "Analizar mi Perfil",
    "matcher.modal.retry": "Probar de nuevo",
    "role.modal.title": "Detalles del Rol",
    "role.modal.close": "Entendido",
    "portal.module.1": "Módulo 1: Fundamentos",
    "portal.module.2": "Módulo 2: Tecnología",
    "portal.module.3": "Módulo 3: Comercial",
    "portal.module.4": "Módulo 4: Práctica",
    "portal.module.1.detail": "Aprende las bases de la financiación pública y nuestro modelo.",
    "portal.module.2.detail": "Domina las herramientas de IA que te permitirán ser 10 veces más productivo.",
    "portal.module.3.detail": "Técnicas de venta y discovery adaptadas a ayudas públicas.",
    "portal.module.4.detail": "Resolución de casos reales y puesta en marcha de tu actividad.",
    "portal.status.locked": "Bloqueado",
    "portal.status.done": "Completado",
    "portal.status.ready": "Listo para empezar",
    "portal.btn.start": "Empezar Módulo",
    "portal.btn.review": "Repasar",
    "module.passed": "¡Módulo Superado!",
    "module.retry": "Necesitas repasar",
    "module.score_msg": "Has acertado {score} de {total} preguntas.",
    "module.next": "Siguiente Módulo",
    "module.repeat": "Repetir Test",
    "module.confirm_btn": "Confirmar Respuesta",
    "welcome.title": "Bienvenido al Programa",
    "welcome.desc": "Estás a punto de iniciar una formación que cambiará tu trayectoria profesional.",
    "welcome.warning": "Este proceso requiere compromiso.",
    "welcome.btn": "Ir a mi Panel",
    "admin.roles.prescriptor": "Ejemplos de venta",
    "admin.roles.colaborador": "Colaborador",
    "admin.roles.delegado_g": "Delegado Gestión",
    "admin.roles.oficina_t": "Oficina Técnica",
    "admin.stats.total": "Candidatos",
    "admin.stats.pending": "Pendientes",
    "admin.stats.approved": "Aprovados",
    "admin.stats.interviews": "Entrevistas",
    "admin.overview.distribution": "Distribución por Roles",
    "admin.overview.recent": "Últimos Candidatos",
    "admin.overview.pending_tasks": "Tareas Urgente",
    "admin.overview.review_desc": "Tienes {count} CVs esperando validación para el nivel Colaborador.",
    "admin.overview.next_interviews": "Próximas Citas",
    "admin.nav.overview": "Resumen",
    "admin.nav.candidates": "Candidatos",
    "admin.nav.interviews": "Calendario",
    "admin.nav.settings": "Ajustes",
    "admin.search.placeholder": "Buscar por nombre o email...",
    "admin.table.candidate": "Candidato",
    "admin.table.role": "Rol",
    "admin.table.status": "Estado",
    "admin.table.progress": "Progreso",
    "admin.table.actions": "Acciones",
    "admin.status.review_cv": "Revisar CV",
    "admin.status.training": "En formación",
    "admin.btn.manage": "Gestionar",
    "admin.btn.schedule_new": "Programar Cita",
    "admin.calendar.title": "Calendario de Entrevistas",
    "admin.calendar.appointments": "Citas para hoy",
    "admin.calendar.empty": "Sin citas",
    "admin.modal.approve": "Aprobar Candidato",
    "admin.modal.discard": "Descartar",
    "admin.modal.schedule_title": "Programar Entrevista",
    "admin.modal.choose": "Seleccionar...",
    "admin.modal.date": "Fecha",
    "admin.modal.time": "Hora",
    "admin.modal.save": "Guardar Cita",
    "admin.modal.saving": "Guardando...",
    "admin.modal.cancel": "Cancelar",
    "admin.settings.tech_params": "Parámetros Técnicos",
    "admin.settings.cutoff": "Nota de Corte Test",
    "admin.settings.maintenance": "Modo Mantenimiento",
    "admin.settings.maintenance_desc": "Bloquea el acceso a candidatos.",
    "admin.settings.sim_guests": "Simulación de Invitados"
  },
  en: {
    "nav.home": "Home",
    "nav.login": "Login",
    "nav.register": "Join Now",
    "nav.logout": "Logout",
    "nav.continue": "Continue Training",
    "hero.tag": "REDESCOMERCIALES.AI",
    "hero.title": "Turn your partner network into an active and scalable sales channel",
    "hero.subtitle": "We activate your indirect commercial network to generate opportunities with pipeline visibility.",
    "hero.bullet1": "More sales without expanding internal team",
    "hero.bullet2": "Active and aligned partners",
    "hero.bullet3": "Full performance control",
    "hero.cta.primary": "Request commercial network diagnosis",
    "hero.cta.secondary": "See how it works",
    "problem.headline": "Your commercial network exists… but it is not activated",
    "problem.copy": "Many B2B companies have partners or collaborators, but without continuous activation or visibility of the indirect pipeline. The strategy is defined; execution across the network is not.",
    "problem.remate": "Result: opportunities that never materialise.",
    "problem.passive.title": "Passive Network (Current)",
    "problem.passive.item1.title": "The 'Ghost' Partner",
    "problem.passive.item1.desc": "A common scenario: a partner registered months ago, with no activity or follow-up since onboarding.",
    "problem.passive.item2.title": "The 'Black Box'",
    "problem.passive.item2.desc": "You know they have clients, but you have no visibility into their pipeline until the sale is lost.",
    "problem.passive.item3.title": "Lack of Focus",
    "problem.passive.item3.desc": "Your partner prioritizes other products because they don't understand your value or how to sell it.",
    "problem.active.title": "Active Network (With us)",
    "problem.active.item1.title": "Proactive Activation",
    "problem.active.item1.desc": "Continuous follow-up and activation so partners report opportunities regularly and traceably.",
    "problem.active.item2.title": "Pipeline visibility",
    "problem.active.item2.desc": "Centralise network activity and the status of each opportunity, without relying on scattered manual updates.",
    "problem.active.item3.title": "Supported execution",
    "problem.active.item3.desc": "Expert operations that maintain network activation and follow-up, so opportunities move forward with process and continuity.",
    "solution.headline": "A system to activate and manage your commercial network",
    "solution.copy": "Methodology, technology and expert operations so your indirect channel generates opportunities with systematic follow-up.",
    "methodology.headline": "Four phases to activate and manage your network",
    "methodology.step1.title": "Phase 1 – Strategic Diagnosis",
    "methodology.step1.desc": "We analyze your current network, potential, and activation gaps.",
    "methodology.step2.title": "Phase 2 – Technological Adaptation",
    "methodology.step2.desc": "We implement a platform adapted to your network: activity tracking, incentives, and lead management.",
    "methodology.step3.title": "Phase 3 – Partner Recruitment",
    "methodology.step3.desc": "We design campaigns to attract new qualified partners.",
    "methodology.step4.title": "Phase 4 – Continuous Management and Activation",
    "methodology.step4.desc": "We operate the network with continuous monitoring, incentivization and optimization to maintain channel execution.",
    "benefits.headline": "What changes when the network is managed systematically",
    "benefits.item1.title": "More pipeline without increasing headcount",
    "benefits.item1.desc": "Generate opportunities through the indirect channel without the fixed costs of a large internal sales force.",
    "benefits.item2.title": "Partners with real activity",
    "benefits.item2.desc": "Move from inactive collaborators to a network with continuous activation, incentives and follow-up.",
    "benefits.item3.title": "Visibility of the indirect channel",
    "benefits.item3.desc": "Centralise your network activity and pipeline to make decisions with better information.",
    "benefits.item4.title": "Scalable and measurable network",
    "benefits.item4.desc": "Consistent processes that let you grow the channel while maintaining control and quality with each addition.",
    "benefits.item5.title": "Results-aligned model",
    "benefits.item5.desc": "Initial investment, ongoing management and a variable component based on indirect channel performance.",
    "diff.headline": "Why this is not just another agency or software",
    "diff.agencies.title": "Agencies",
    "diff.agencies.desc": "They generate leads but don't activate networks",
    "diff.saas.title": "SaaS",
    "diff.saas.desc": "They give you tools, but no execution",
    "diff.us.title": "Redescomerciales.ai",
    "diff.us.desc": "Complete system: strategy + technology + operation",
    "cases.headline": "Designed for companies that want to scale without increasing fixed costs",
    "cases.metric1.val": "Activation",
    "cases.metric1.label": "Systematic for partners and collaborators",
    "cases.metric2.val": "Visibility",
    "cases.metric2.label": "Of the indirect pipeline",
    "cases.metric3.val": "Opportunities",
    "cases.metric3.label": "Generated from the commercial network",
    "model.headline": "A model aligned with results",
    "model.copy": "We work with a hybrid model: initial setup, monthly management fee, and variable based on results.",
    "model.remate": "We win when you sell.",
    "whatIs.title": "What is Redescomerciales.ai?",
    "whatIs.text": "Redescomerciales.ai helps B2B companies activate and manage their indirect commercial network. We combine diagnosis, follow-up, methodology and technology to generate opportunities with pipeline visibility and a clearer view of channel impact.",
    "trust.label": "Sectors we work with",
    "trust.sector1": "B2B SaaS",
    "trust.sector2": "Consulting",
    "trust.sector3": "Professional services",
    "trust.sector4": "Investment funds",
    "trust.sector5": "Scale-ups",
    "faq.title": "Clearing doubts",
    "faq.q1": "Do I need to have a network already?",
    "faq.a1": "Not necessarily. Many companies have underused contacts; others start from scratch. In both cases we design structure, incentives and tracking to activate or build the commercial network.",
    "faq.q2": "How long does it take to see results?",
    "faq.a2": "First activation indicators usually appear within weeks. Sustained commercial impact consolidates over months, depending on network size, sector and internal involvement.",
    "faq.q3": "What type of companies fit?",
    "faq.a3": "B2B companies with a structured sales cycle: SaaS, consulting, professional services, investment funds and scale-ups looking to grow indirect sales without increasing fixed costs.",
    "faq.q4": "What does it involve for my team internally?",
    "faq.a4": "Little operational burden. We activate the network, handle follow-up and you validate opportunities. The platform centralises visibility of the indirect channel.",
    "faq.q5": "Why isn't our CRM or current tools enough?",
    "faq.a5": "A CRM stores information but does not activate or operate the network. We add the activation model, systematic follow-up and indirect pipeline visibility that your tools typically do not cover.",
    "faq.q6": "How can I request a diagnosis?",
    "faq.a6": "From the contact page, tell us about your situation. We respond within 24 business hours, review your network and, if it fits, schedule a diagnosis session to propose an activation plan.",
    "faq.q7": "Do you only work in Spain?",
    "faq.a7": "We are based in Barcelona and mainly work with companies in Spain and Europe. The model applies to any B2B company with a commercial network or potential to build one.",
    "faq.q8": "Is it a CRM, a consultancy or a partner platform?",
    "faq.a8": "It is a system that combines methodology, technology and operations to activate and follow your indirect network. The platform provides visibility; the team executes the model.",
    "faq.q9": "How is success measured?",
    "faq.a9": "Through network activation indicators, partner activity and indirect pipeline evolution. Follow-up is centralised so you can review what works and make decisions.",
    "faq.q10": "Does it fit with the tools we already use?",
    "faq.a10": "It does not necessarily replace your CRM or internal systems. It complements what you already have by centralising activation and follow-up of the indirect channel.",
    "contact.faqLink": "See all frequently asked questions",
    "breadcrumb.home": "Home",
    "cta.final.title": "Can your commercial network generate more opportunities?",
    "cta.final.subtitle": "In one session we review your network, identify activation gaps and show you how to gain more visibility of the indirect pipeline.",
    "cta.final.btn": "Request commercial network diagnosis",
    "support.marketing": "Marketing Support",
    "support.subject": "Subject",
    "support.inquiry": "Inquiry Details",
    "support.placeholder_subject": "How can we help you?",
    "support.placeholder_inquiry": "Describe your marketing needs in detail...",
    "support.send": "Send Inquiry",
    "support.success": "Inquiry sent successfully. Our team will contact you shortly.",
    "login.title": "Welcome back",
    "login.subtitle": "Access your management panel and continue your training.",
    "login.email": "Email Address",
    "login.email_placeholder": "you@email.com",
    "login.password": "Password",
    "login.pass_placeholder": "••••••••",
    "login.btn": "Enter Portal",
    "login.forgot": "Forgot your password?",
    "login.new": "New to Redescomerciales.ai?",
    "login.register_link": "Create professional account",
    "login.recovery_title": "Recover account",
    "login.recovery_subtitle": "We will send you a recovery link",
    "login.back": "Back",
    "login.recovery_success": "Email sent successfully",
    "login.recovery_error_email": "Please enter your email address",
    "register.title": "Create your account",
    "register.subtitle": "Join the leading platform in B2B channel activation.",
    "register.name": "Full Name",
    "register.name_placeholder": "Your name",
    "register.email": "Email",
    "register.email_placeholder": "you@email.com",
    "register.phone": "Phone",
    "register.phone_placeholder": "600 000 000",
    "register.level": "Desired level",
    "register.pass": "Password",
    "register.pass_placeholder": "••••••••",
    "register.pass_confirm": "Repeat password",
    "register.btn": "Create professional account",
    "register.existing": "Already have an account?",
    "register.login_link": "IDENTIFY HERE",
    "register.email_sent_title": "CHECK YOUR EMAIL!",
    "register.email_sent_desc": "We have sent a confirmation link to",
    "register.role.1": "1 - Prescriber",
    "register.role.2": "2 - Collaborator",
    "register.role.3": "3 - Delegate (Management)",
    "register.role.4": "4 - Delegate (Technical Office)",
    "portal.title": "Career Dashboard",
    "portal.subtitle": "Follow your professional itinerary.",
    "footer.rights": "Redescomerciales.ai - All rights reserved.",
    "ecosystem.title": "Our Ecosystem",
    "ecosystem.subtitle": "Four collaboration levels adapted to your profile.",
    "role.1.title": "Prescriber",
    "role.1.desc": "Recommend Redescomerciales.ai to your network and get passive benefits for each success.",
    "role.1.subtitle": "Ideal for senior professionals with a good network of contacts who want to generate extra income without operational burden.",
    "role.1.perfil_title": "IDEAL PROFILE",
    "role.1.perfil_desc": "Person who wants to monetize their contacts. Consultants or professionals from any sector.",
    "role.1.economico_title": "ECONOMIC MODEL",
    "role.1.economico_desc": "No entry cost (€0). You commission 7.5% on the closing of each agreement.",
    "role.1.funciones_title": "YOUR MAIN FUNCTIONS",
    "role.1.f1": "Identify contacts.",
    "role.1.f2": "Present the opportunity.",
    "role.1.f3": "Our team closes the sale.",
    "role.1.ejemplo_title": "Real Example",
    "role.1.ejemplo_desc": "\"Case Jorge (55 years old): Consultant who monetizes his old agenda by referring companies to Redescomerciales.ai without getting involved in management.\"",
    "role.2.title": "Collaborator",
    "role.2.desc": "Manage your own client portfolio and lead the commercial process with our technology.",
    "role.2.subtitle": "Ideal for consultants and sales reps who want to lead the sales process with their own technology.",
    "role.2.perfil_title": "IDEAL PROFILE",
    "role.2.perfil_desc": "Multi-portfolio commercial, advisor or marketing agency with active client portfolio.",
    "role.2.economico_title": "ECONOMIC MODEL",
    "role.2.economico_desc": "Annual fee of €3,000. 15% commission on net fees.",
    "role.2.funciones_title": "YOUR MAIN FUNCTIONS",
    "role.2.f1": "Identify qualified leads.",
    "role.2.f2": "Perform initial discovery.",
    "role.2.f3": "Close commercial agreements.",
    "role.2.ejemplo_title": "Real Example",
    "role.2.ejemplo_desc": "\"Case Elena: Insurance agency offering Redescomerciales.ai as a value-added service to its SME clients.\"",
    "role.3.title": "Delegate",
    "role.3.sub": "MANAGEMENT",
    "role.3.desc": "Lead a geographic area and coordinate prescriber networks under our franchise model.",
    "role.3.subtitle": "Lead an exclusive geographic area and coordinate prescriber networks under our model.",
    "role.3.perfil_title": "IDEAL PROFILE",
    "role.3.perfil_desc": "Entrepreneur or ex-executive with management and commercial team leadership capacity.",
    "role.3.economico_title": "ECONOMIC MODEL",
    "role.3.economico_desc": "Fee of €12,000/year. 30% commission and territorial control.",
    "role.3.funciones_title": "YOUR MAIN FUNCTIONS",
    "role.3.f1": "Recruit and train prescribers.",
    "role.3.f2": "Strategic territorial management.",
    "role.3.f3": "Official brand representation.",
    "role.3.ejemplo_title": "Real Example",
    "role.3.ejemplo_desc": "\"Case Manuel: Ex-bank director managing the province of Valencia with a network of 50 prescribers.\"",
    "role.4.title": "Delegate",
    "role.4.sub": "TECHNICAL OFFICE",
    "role.4.desc": "The most advanced level. Total commercial management and technical writing with next-gen AI.",
    "role.4.subtitle": "The level of total control. Commercial management and technical writing assisted by AI.",
    "role.4.perfil_title": "IDEAL PROFILE",
    "role.4.perfil_desc": "Established consultants or R&D experts looking to maximize profitability.",
    "role.4.economico_title": "ECONOMIC MODEL",
    "role.4.economico_desc": "Technical office model. Maximum commission (up to 40%) for total control.",
    "role.4.funciones_title": "YOUR MAIN FUNCTIONS",
    "role.4.f1": "Technical writing with own AI.",
    "role.4.f2": "Technical validation of files.",
    "role.4.f3": "Premium commercial management.",
    "role.4.ejemplo_title": "Real Example",
    "role.4.ejemplo_desc": "\"Case TechConsult: Consultancy that has 10x its production using Redescomerciales.ai.\"",
    "portal.btn.info": "Learn more",
    "matcher.title": "AI Career Matcher",
    "matcher.desc": "Don't know which level to choose? Tell our AI about your experience and it will find your ideal role.",
    "matcher.btn": "Try AI Matcher",
    "matcher.modal.title": "Career Assistant",
    "matcher.modal.placeholder": "E.g.: I am a sales rep with 10 years of experience in banking and I have many contacts in the industrial sector...",
    "matcher.modal.loading": "Analyzing your profile...",
    "matcher.modal.btn": "Analyze my Profile",
    "matcher.modal.retry": "Try again",
    "role.modal.title": "Role Details",
    "role.modal.close": "Understood",
    "portal.module.1": "Module 1: Fundamentals",
    "portal.module.2": "Module 2: Technology",
    "portal.module.3": "Module 3: Commercial",
    "portal.module.4": "Module 4: Practical",
    "portal.module.1.detail": "Learn the basics of public funding and the Redescomerciales.ai model.",
    "portal.module.2.detail": "Master the AI tools that will allow you to be 10x more productive.",
    "portal.module.3.detail": "Sales and discovery techniques adapted to public aid.",
    "portal.module.4.detail": "Resolution of real cases and starting your activity.",
    "portal.status.locked": "Locked",
    "portal.status.done": "Completed",
    "portal.status.ready": "Ready to start",
    "portal.btn.start": "Start Module",
    "portal.btn.review": "Review",
    "module.passed": "Module Passed!",
    "module.retry": "Need to review",
    "module.score_msg": "You got {score} out of {total} questions correct.",
    "module.next": "Next Module",
    "module.repeat": "Repeat Test",
    "module.confirm_btn": "Confirm Answer",
    "welcome.title": "Welcome to the Program",
    "welcome.desc": "You are about to start a training that will change your professional career.",
    "welcome.warning": "This process requires commitment.",
    "welcome.btn": "Go to Dashboard",
    "admin.roles.prescriptor": "Prescriber",
    "admin.roles.colaborador": "Collaborator",
    "admin.roles.delegado_g": "Management Delegate",
    "admin.roles.oficina_t": "Technical Office",
    "admin.stats.total": "Candidates",
    "admin.stats.pending": "Pending",
    "admin.stats.approved": "Approved",
    "admin.stats.interviews": "Interviews",
    "admin.overview.distribution": "Role Distribution",
    "admin.overview.recent": "Recent Candidates",
    "admin.overview.pending_tasks": "Urgent Tasks",
    "admin.overview.review_desc": "You have {count} CVs waiting for validation for the Collaborator level.",
    "admin.overview.next_interviews": "Next Appointments",
    "admin.nav.overview": "Overview",
    "admin.nav.candidates": "Candidates",
    "admin.nav.interviews": "Calendar",
    "admin.nav.settings": "Settings",
    "admin.search.placeholder": "Search by name or email...",
    "admin.table.candidate": "Candidate",
    "admin.table.role": "Role",
    "admin.table.status": "Status",
    "admin.table.progress": "Progress",
    "admin.table.actions": "Actions",
    "admin.status.review_cv": "Review CV",
    "admin.status.training": "Training",
    "admin.btn.manage": "Manage",
    "admin.btn.schedule_new": "Schedule Appt",
    "admin.calendar.title": "Interview Calendar",
    "admin.calendar.appointments": "Today's Appts",
    "admin.calendar.empty": "No appointments",
    "admin.modal.approve": "Approve Candidate",
    "admin.modal.discard": "Discard",
    "admin.modal.schedule_title": "Schedule Interview",
    "admin.modal.choose": "Select...",
    "admin.modal.date": "Date",
    "admin.modal.time": "Time",
    "admin.modal.save": "Save Appt",
    "admin.modal.saving": "Saving...",
    "admin.modal.cancel": "Cancel",
    "admin.settings.tech_params": "Technical Parameters",
    "admin.settings.cutoff": "Test Cutoff Score",
    "admin.settings.maintenance": "Maintenance Mode",
    "admin.settings.maintenance_desc": "Blocks candidate access.",
    "admin.settings.sim_guests": "Guest Simulation"
  },
  ca: {
    "nav.home": "Inici",
    "nav.login": "Iniciar Sessió",
    "nav.register": "Unir-se Ara",
    "nav.logout": "Sortir",
    "nav.continue": "Continuar Formació",
    "hero.tag": "PROGRAMA OFICIAL",
    "hero.title": "Uneix-te a l'Ecosistema Redescomerciales.ai",
    "hero.subtitle": "Descobreix una oportunitat real en un mercat de 400.000M€. Formem els líders del finançament públic del futur.",
    "hero.btn": "Unir-se Ara",
    "login.title": "Benvingut de nou",
    "login.subtitle": "Accedeix al teu panell de gestió i continua la teva formació.",
    "login.email": "Correu Electrònic",
    "login.email_placeholder": "tu@email.com",
    "login.password": "Contrasenya",
    "login.pass_placeholder": "••••••••",
    "login.btn": "Entrar al Portal",
    "login.forgot": "Has oblidat la contrasenya?",
    "login.new": "Nou a Redescomerciales.ai?",
    "login.register_link": "Crear compte professional",
    "login.recovery_title": "Recuperar compte",
    "login.recovery_subtitle": "T'enviarem un enllaç de recuperació",
    "login.back": "Tornar",
    "login.recovery_success": "Correu enviat correctament",
    "login.recovery_error_email": "Introdueix el teu correu electrònic",
    "register.title": "Crea el teu compte",
    "register.subtitle": "Uneix-te a l'ecosistema líder en gestió d'ajuts públics.",
    "register.name": "Nom Complet",
    "register.name_placeholder": "El teu nom",
    "register.email": "Email",
    "register.email_placeholder": "tu@email.com",
    "register.phone": "Telèfon",
    "register.phone_placeholder": "600 000 000",
    "register.level": "Nivell desitjat",
    "register.pass": "Contrasenya",
    "register.pass_placeholder": "••••••••",
    "register.pass_confirm": "Repetir contrasenya",
    "register.btn": "Crear compte professional",
    "register.existing": "Ja tens compte?",
    "register.login_link": "IDENTIFICA'T AQUÍ",
    "register.email_sent_title": "REVISA EL TEU CORREU!",
    "register.email_sent_desc": "Hem enviat un enllaç de confirmació a",
    "register.role.1": "1 - Ejemplos de venta",
    "register.role.2": "2 - Col·laborador",
    "register.role.3": "3 - Delegat (Gestió)",
    "register.role.4": "4 - Delegat (Oficina Tècnica)",
    "portal.title": "Panell de Carrera",
    "portal.subtitle": "Segueix el teu itinerari professional.",
    "footer.rights": "Líders en Finançament Públic. Tots els drets reservats.",
    "ecosystem.title": "El nostre Ecosistema",
    "ecosystem.subtitle": "Quatre nivells de col·laboració adaptats al teu perfil.",
    "role.1.title": "Ejemplos de venta",
    "role.1.desc": "Recomana Redescomerciales.ai a la teva xarxa de contactes i obté beneficis passius per cada èxit.",
    "role.1.subtitle": "Ideal per a professionals sènior amb una bona xarxa de contactes que volen generar ingressos extra.",
    "role.1.perfil_title": "PERFIL IDEAL",
    "role.1.perfil_desc": "Persona que vulgui monetitzar els seus contactes. Consultors o professionals de qualsevol sector.",
    "role.1.economico_title": "MODEL ECONÓMICO",
    "role.1.economico_desc": "Sense cost d'entrada (0€). Comisiones un 7,5% sobre el tancament de cada conveni.",
    "role.1.funciones_title": "LES TEVES FUNCIONS PRINCIPALS",
    "role.1.f1": "Identificar contactes.",
    "role.1.f2": "Presentar l'oportunitat.",
    "role.1.f3": "El nostre equip tanca la venda.",
    "role.1.ejemplo_title": "Exemple Real",
    "role.1.ejemplo_desc": "\"Cas Jorge (55 anys): Consultor que monetitza la seva antiga agenda referint empreses a Redescomerciales.ai.\"",
    "role.2.title": "Col·laborador",
    "role.2.desc": "Gestiona la teva pròpia cartera de clients i lidera el procés comercial amb la nostra tecnologia.",
    "role.2.subtitle": "Ideal per a consultors i comercials que volen liderar el procés de venda.",
    "role.2.perfil_title": "PERFIL IDEAL",
    "role.2.perfil_desc": "Comercial multicartera, assessor o agència de màrqueting amb cartera activa.",
    "role.2.economico_title": "MODEL ECONÓMICO",
    "role.2.economico_desc": "Cànon anual de 3.000€. Comissió del 15% sobre honoraris nets.",
    "role.2.funciones_title": "LES TEVES FUNCIONS PRINCIPALS",
    "role.2.f1": "Identificar leads qualificats.",
    "role.2.f2": "Realitzar el discovery inicial.",
    "role.2.f3": "Tancar convenis comercials.",
    "role.2.ejemplo_title": "Exemple Real",
    "role.2.ejemplo_desc": "\"Cas Elena: Agència d'assegurances que ofereix Redescomerciales.ai com a servei de valor afegit.\"",
    "role.3.title": "Delegat",
    "role.3.sub": "GESTIÓ",
    "role.3.desc": "Lidera una zona geogràfica i coordina xarxes de Ejemplos de venta sota el nostre model de franquícia.",
    "role.3.subtitle": "Lidera una zona geogràfica exclusiva i coordina xarxes de Ejemplos de venta.",
    "role.3.perfil_title": "PERFIL IDEAL",
    "role.3.perfil_desc": "Emprenedor o ex-directiu amb capacitat de gestió i lideratge d'equips.",
    "role.3.economico_title": "MODEL ECONÓMICO",
    "role.3.economico_desc": "Cànon de 12.000€/año. Comissió del 30% i control territorial.",
    "role.3.funciones_title": "LES TEVES FUNCIONS PRINCIPALS",
    "role.3.f1": "Reclutar i formar Ejemplos de venta.",
    "role.3.f2": "Gestió estratègica territorial.",
    "role.3.f3": "Representació oficial de la marca.",
    "role.3.ejemplo_title": "Exemple Real",
    "role.3.ejemplo_desc": "\"Cas Manuel: Ex-director de banca que gestiona la província de València.\"",
    "role.4.title": "Delegat",
    "role.4.sub": "OFICINA TÈCNICA",
    "role.4.desc": "El nivell més avanzado. Gestió comercial total i redaccío d'expedients amb IA d'última generació.",
    "role.4.subtitle": "El nivell de control total. Gestió comercial i redacció tècnica assistida por IA.",
    "role.4.perfil_title": "PERFIL IDEAL",
    "role.4.perfil_desc": "Consultores establertes o experts en R+D que busquen maximitzar rentabilitat.",
    "role.4.economico_title": "MODEL ECONÓMICO",
    "role.4.economico_desc": "Model d'oficina tècnica. Màxima comissió (fins al 40%) per control total.",
    "role.4.funciones_title": "LES TEVES FUNCIONS PRINCIPALS",
    "role.4.f1": "Redacción tècnica amb IA pròpia.",
    "role.4.f2": "Validació tècnica d'expedients.",
    "role.4.f3": "Gestió comercial premium.",
    "role.4.ejemplo_title": "Exemple Real",
    "role.4.ejemplo_desc": "\"Cas TechConsult: Consultoria que ha multiplicat per 10 la seva producció.\"",
    "portal.btn.info": "Saber-ne més",
    "matcher.title": "Matcher de Carrera IA",
    "matcher.desc": "No saps quin nivell triar? Explica a la nostra IA la teva experiència i et dirà quin és el teu rol ideal.",
    "matcher.btn": "Provar Matcher IA",
    "matcher.modal.title": "Assistent de Carrera",
    "matcher.modal.placeholder": "Ex: Sóc comercial amb 10 anys d'experiència en banca i tinc molts contactes...",
    "matcher.modal.loading": "Analitzant el teu perfil...",
    "matcher.modal.btn": "Analitzar el meu Perfil",
    "matcher.modal.retry": "Provar de nou",
    "role.modal.title": "Detalls del Rol",
    "role.modal.close": "Entès",
    "portal.module.1": "Mòdul 1: Fonaments",
    "portal.module.2": "Mòdul 2: Tecnologia",
    "portal.module.3": "Mòdul 3: Comercial",
    "portal.module.4": "Mòdul 4: Pràctica",
    "portal.module.1.detail": "Aprèn les bases del finançament públic i el model Redescomerciales.ai.",
    "portal.module.2.detail": "Domina les eines d'IA que et permetran ser 10 vegades més productiu.",
    "portal.module.3.detail": "Tècniques de venda i discovery adaptades a ajuts públics.",
    "portal.module.4.detail": "Resolució de casos reals i posada en marxa de la teva activitat.",
    "portal.status.locked": "Bloquejat",
    "portal.status.done": "Completat",
    "portal.status.ready": "Llest per començar",
    "portal.btn.start": "Començar Mòdul",
    "portal.btn.review": "Repassar",
    "module.passed": "Mòdul Superat!",
    "module.retry": "Necessites repassar",
    "module.score_msg": "Has encertat {score} de {total} preguntes.",
    "module.next": "Següent Mòdul",
    "module.repeat": "Repetir Test",
    "module.confirm_btn": "Confirmar Resposta",
    "welcome.title": "Benvingut al Programa",
    "welcome.desc": "Estàs a punt d'iniciar una formació que canviarà la teva trajectòria professional.",
    "welcome.warning": "Aquest procés requereix compromís.",
    "welcome.btn": "Anar al meu Panell",
    "admin.roles.prescriptor": "Ejemplos de venta",
    "admin.roles.colaborador": "Col·laborador",
    "admin.roles.delegado_g": "Delegat Gestió",
    "admin.roles.oficina_t": "Oficina Tècnica",
    "admin.stats.total": "Candidats",
    "admin.stats.pending": "Pendents",
    "admin.stats.approved": "Aprovats",
    "admin.stats.interviews": "Entrevistes",
    "admin.overview.distribution": "Distribució per Rols",
    "admin.overview.recent": "Últims Candidatos",
    "admin.overview.pending_tasks": "Tasques Urgent",
    "admin.overview.review_desc": "Tens {count} CV esperant validació per al nivell Col·laborador.",
    "admin.overview.next_interviews": "Properes Cites",
    "admin.nav.overview": "Resum",
    "admin.nav.candidates": "Candidats",
    "admin.nav.interviews": "Calendari",
    "admin.nav.settings": "Ajustos",
    "admin.search.placeholder": "Cercar per nom o email...",
    "admin.table.candidate": "Candidat",
    "admin.table.role": "Rol",
    "admin.table.status": "Estat",
    "admin.table.progress": "Progrés",
    "admin.table.actions": "Accions",
    "admin.status.review_cv": "Revisar CV",
    "admin.status.training": "En formació",
    "admin.btn.manage": "Gestionar",
    "admin.btn.schedule_new": "Programar Cita",
    "admin.calendar.title": "Calendari d'Entrevistes",
    "admin.calendar.appointments": "Cites per avui",
    "admin.calendar.empty": "Sense cites",
    "admin.modal.approve": "Aprovar Candidat",
    "admin.modal.discard": "Descartar",
    "admin.modal.schedule_title": "Programar Entrevista",
    "admin.modal.choose": "Seleccionar...",
    "admin.modal.date": "Data",
    "admin.modal.time": "Hora",
    "admin.modal.save": "Guardar Cita",
    "admin.modal.saving": "Guardant...",
    "admin.modal.cancel": "Cancel·lar",
    "admin.settings.tech_params": "Paràmetres Tècnics",
    "admin.settings.cutoff": "Nota de Tall Test",
    "admin.settings.maintenance": "Mode Manteniment",
    "admin.settings.maintenance_desc": "Bloqueja l'accés a candidats.",
    "admin.settings.sim_guests": "Simulació de Convidats"
  },
};


Object.assign(translations.es, landingEs);
Object.assign(translations.en, landingEn);
Object.assign(translations.ca, landingCa);
Object.assign(translations.ca, portalCa);

const SettingsContext = createContext<SettingsContextType | undefined>(undefined);

const SUPPORTED_LANGS: Language[] = ['es', 'en', 'ca'];

const getInitialTheme = (): Theme => {
  const stored = localStorage.getItem('gw_theme') as Theme | null;
  if (stored === 'light' || stored === 'dark') return stored;
  if (typeof window !== 'undefined' && window.matchMedia('(prefers-color-scheme: dark)').matches) {
    return 'dark';
  }
  return 'light';
};

const applyThemeClass = (theme: Theme) => {
  document.documentElement.classList.toggle('dark', theme === 'dark');
  document.documentElement.style.colorScheme = theme;
};

export const SettingsProvider = ({ children }: { children?: ReactNode }) => {
  const [lang, setLangState] = useState<Language>(() => {
    const stored = localStorage.getItem('gw_lang') as Language | null;
    return stored && SUPPORTED_LANGS.includes(stored) ? stored : 'es';
  });
  const [theme, setThemeState] = useState<Theme>(getInitialTheme);

  useEffect(() => {
    localStorage.setItem('gw_lang', lang);
    document.documentElement.lang = lang;
  }, [lang]);

  useEffect(() => {
    localStorage.setItem('gw_theme', theme);
    applyThemeClass(theme);
  }, [theme]);

  const toggleTheme = () => setThemeState(prev => prev === 'light' ? 'dark' : 'light');
  const setLang = (l: Language) => setLangState(l);
  
  const t = (key: string) => translations[lang][key] || translations['es'][key] || key;

  return (
    <SettingsContext.Provider value={{ lang, theme, setLang, toggleTheme, t }}>
      {children}
    </SettingsContext.Provider>
  );
};

export const useSettings = () => {
  const context = useContext(SettingsContext);
  if (!context) throw new Error('useSettings must be used within SettingsProvider');
  return context;
};
