
import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'es' | 'en' | 'ca' | 'fr' | 'de' | 'it';
type Theme = 'light' | 'dark';

interface SettingsContextType {
  lang: Language;
  theme: Theme;
  setLang: (lang: Language) => void;
  toggleTheme: () => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  es: {
    "nav.home": "Inicio",
    "nav.login": "Iniciar Sesión",
    "nav.register": "Unirse Ahora",
    "nav.logout": "Salir",
    "nav.continue": "Continuar Formación",
    "hero.tag": "REDESCOMERCIALES.AI",
    "hero.title": "Convierte tu red de partners en un canal de ventas activo y escalable",
    "hero.subtitle": "La plataforma impulsada por IA que identifica, motiva y cierra ventas a través de tus partners. Todo bajo tu control y en un solo panel",
    "hero.bullet1": "Más ventas sin ampliar equipo interno",
    "hero.bullet2": "Partners activos y alineados",
    "hero.bullet3": "Control total del rendimiento",
    "hero.cta.primary": "Solicitar diagnóstico gratuito",
    "hero.cta.secondary": "Ver cómo funciona",
    "problem.headline": "Tu red comercial existe… pero no vende como debería",
    "problem.copy": "La mayoría de empresas B2B tienen partners o distribuidores, pero no están activados, no tienen incentivos claros y no generan pipeline real.",
    "problem.remate": "Resultado: oportunidad perdida constante.",
    "problem.passive.title": "Red Pasiva (Actual)",
    "problem.passive.item1.title": "El Partner 'Fantasma'",
    "problem.passive.item1.desc": "Se registró hace 6 meses. 0 leads reportados. No hay contacto desde el onboarding.",
    "problem.passive.item2.title": "La 'Caja Negra'",
    "problem.passive.item2.desc": "Sabes que tienen clientes, pero no tienes visibilidad de su pipeline hasta que la venta se pierde.",
    "problem.passive.item3.title": "Falta de Foco",
    "problem.passive.item3.desc": "Tu partner prioriza otros productos porque no entiende tu valor o no sabe cómo venderlo.",
    "problem.active.title": "Red Activa (Con nosotros)",
    "problem.active.item1.title": "Activación Proactiva",
    "problem.active.item1.desc": "Alertas automáticas y formación continua. El partner reporta 2-3 leads cualificados al mes.",
    "problem.active.item2.title": "Transparencia Total",
    "problem.active.item2.desc": "Dashboard en tiempo real. El partner ve sus comisiones y el estado de cada operación.",
    "problem.active.item3.title": "Cierre Acompañado",
    "problem.active.item3.desc": "Soporte experto de Redescomerciales.ai para ayudar al partner a cerrar ventas complejas.",
    "solution.headline": "Activamos tu red comercial con metodología + tecnología",
    "solution.copy": "No somos una agencia ni un SaaS. Somos un sistema completo para convertir tu red en ventas.",
    "methodology.headline": "Un sistema probado en 4 fases",
    "methodology.step1.title": "Fase 1 – Diagnóstico estratégico",
    "methodology.step1.desc": "Analizamos tu red actual, potencial y gaps de activación.",
    "methodology.step2.title": "Fase 2 – Adaptación tecnológica",
    "methodology.step2.desc": "Implementamos una plataforma adaptada a tu red: tracking de actividad, incentivos y gestión de leads.",
    "methodology.step3.title": "Fase 3 – Captación de colaboradores",
    "methodology.step3.desc": "Diseñamos campañas para atraer nuevos partners cualificados.",
    "methodology.step4.title": "Fase 4 – Gestión y activación continua",
    "methodology.step4.desc": "Operamos tu red para maximizar resultados: seguimiento, incentivación y optimización.",
    "benefits.headline": "Resultados que impactan directamente en tu facturación",
    "benefits.item1.title": "Incremento del pipeline sin aumentar plantilla",
    "benefits.item1.desc": "Multiplica tus oportunidades comerciales apalancándote en redes externas sin los costes fijos de una gran fuerza de ventas propia.",
    "benefits.item2.title": "Activación real de partners dormidos",
    "benefits.item2.desc": "Transformamos tu base de datos de colaboradores inactivos en un motor de generación de leads constante mediante incentivos y seguimiento.",
    "benefits.item3.title": "Mayor previsibilidad comercial",
    "benefits.item3.desc": "Obtén visibilidad total del pipeline indirecto con datos en tiempo real para tomar mejores decisiones estratégicas.",
    "benefits.item4.title": "Red escalable y medible",
    "benefits.item4.desc": "Diseñamos procesos que permiten crecer sin límites, manteniendo la misma calidad y control en cada nueva incorporación.",
    "benefits.item5.title": "Reducción del coste de adquisición",
    "benefits.item5.desc": "Optimiza tu inversión en marketing y ventas pagando solo por resultados reales y acuerdos cerrados por tu red.",
    "diff.headline": "Por qué esto no es una agencia ni un software más",
    "diff.agencies.title": "Agencias",
    "diff.agencies.desc": "Generan leads pero no activan redes",
    "diff.saas.title": "SaaS",
    "diff.saas.desc": "Te dan herramientas, pero no ejecución",
    "diff.us.title": "Redescomerciales.ai",
    "diff.us.desc": "Sistema completo: estrategia + tecnología + operación",
    "cases.headline": "Diseñado para empresas que quieren escalar sin aumentar costes fijos",
    "cases.metric1.val": "+40%",
    "cases.metric1.label": "activación de partners",
    "cases.metric2.val": "+250",
    "cases.metric2.label": "leads generados",
    "cases.metric3.val": "+1.2M€",
    "cases.metric3.label": "pipeline",
    "model.headline": "Un modelo alineado a resultados",
    "model.copy": "Trabajamos con un modelo híbrido: setup inicial, fee mensual de gestión y variable sobre resultados.",
    "model.remate": "Ganamos cuando tú vendes.",
    "faq.title": "Despejando dudas",
    "faq.q1": "¿Necesito tener ya una red?",
    "faq.a1": "No, también la creamos desde cero.",
    "faq.q2": "¿Cuánto tarda en verse resultados?",
    "faq.a2": "Primeros indicadores en semanas, impacto real en meses.",
    "faq.q3": "¿Qué tipo de empresas encajan?",
    "faq.a3": "B2B con ciclo comercial estructurado.",
    "faq.q4": "¿Qué implica internamente?",
    "faq.a4": "Mínima dedicación, nosotros operamos.",
    "cta.final.title": "Descubre el potencial real de tu red comercial",
    "cta.final.subtitle": "Te mostramos en una sesión cómo activar tu red y generar más ventas sin aumentar estructura.",
    "cta.final.btn": "Solicitar diagnóstico estratégico",
    "support.marketing": "Soporte Marketing",
    "support.subject": "Asunto",
    "support.inquiry": "Consulta a realizar",
    "support.placeholder_subject": "¿En qué podemos ayudarte?",
    "support.placeholder_inquiry": "Describe detalladamente tu necesidad de marketing...",
    "support.send": "Enviar Consulta",
    "support.success": "Consulta enviada correctamente. Nuestro equipo contactará contigo pronto.",
    "login.title": "Bienvenido de nuevo",
    "login.subtitle": "Accede de tu panel de gestión y continúa tu formación en el ecosistema.",
    "login.email": "Correo Electrónico",
    "login.email_placeholder": "tu@email.com",
    "login.password": "Contraseña",
    "login.pass_placeholder": "••••••••",
    "login.btn": "Entrar al Portal",
    "login.forgot": "¿Has olvidado tu contraseña?",
    "login.new": "¿Nuevo aquí?",
    "login.register_link": "Crear cuenta profesional",
    "login.recovery_title": "Recuperar cuenta",
    "login.recovery_subtitle": "Te enviaremos un enlace de recuperación",
    "login.back": "Volver",
    "login.recovery_success": "Correo enviado correctamente",
    "login.recovery_error_email": "Introduce tu correo electrónico",
    "register.title": "Crea tu cuenta",
    "register.subtitle": "Únete a la plataforma líder en activación de canales B2B.",
    "register.name": "Nombre Completo",
    "register.name_placeholder": "Tu nombre",
    "register.email": "Email",
    "register.email_placeholder": "tu@email.com",
    "register.phone": "Teléfono",
    "register.phone_placeholder": "600 000 000",
    "register.level": "Nivel deseado",
    "register.pass": "Contraseña",
    "register.pass_placeholder": "••••••••",
    "register.pass_confirm": "Repetir contraseña",
    "register.btn": "Crear cuenta profesional",
    "register.existing": "¿Ya tienes cuenta?",
    "register.login_link": "IDENTIFÍCATE AQUÍ",
    "register.email_sent_title": "¡REVISA TU CORREO!",
    "register.email_sent_desc": "Hemos enviado un enlace de confirmación a",
    "register.role.1": "1 - Ejemplos de venta",
    "register.role.2": "2 - Colaborador",
    "register.role.3": "3 - Delegado (Gestión)",
    "register.role.4": "4 - Delegado (Oficina Técnica)",
    "portal.title": "Panel de Carrera",
    "portal.subtitle": "Sigue tu itinerario profesional.",
    "footer.rights": "Redescomerciales.ai - Todos los derechos reservados.",
    "ecosystem.title": "Nuestro Ecosistema",
    "ecosystem.subtitle": "Cuatro niveles de colaboración adaptados para tu perfil.",
    "role.1.title": "Ejemplos de venta",
    "role.1.desc": "Recomienda nuestra plataforma a tu red de contactos y obtén beneficios pasivos por cada éxito.",
    "role.1.subtitle": "Ideal para profesionales senior con una buena red de contactos que quieren generar ingresos extra sin carga operativa.",
    "role.1.perfil_title": "PERFIL IDEAL",
    "role.1.perfil_desc": "Persona que quiera monetizar sus contactos. Consultores o profesionales de cualquier sector.",
    "role.1.economico_title": "MODELO ECONÓMICO",
    "role.1.economico_desc": "Sin coste de entrada (0€). Comisionas un 7,5% sobre el cierre de cada convenio.",
    "role.1.funciones_title": "TUS FUNCIONES PRINCIPALES",
    "role.1.f1": "Identificar contactos.",
    "role.1.f2": "Presentar la oportunidad.",
    "role.1.f3": "Nuestro equipo cierra la venta.",
    "role.1.ejemplo_title": "Ejemplo Real",
    "role.1.ejemplo_desc": "\"Caso Jorge (55 años): Consultor que monetiza su antigua agenda refiriendo empresas a nuestra plataforma sin involucrarse en la gestión.\"",
    "role.2.title": "Colaborador",
    "role.2.desc": "Gestiona tu propia cartera de clientes y lidera el proceso comercial con nuestra tecnología.",
    "role.2.subtitle": "Ideal para consultores y comerciales que quieren liderar el proceso de venta con tecnología propia.",
    "role.2.perfil_title": "PERFIL IDEAL",
    "role.2.perfil_desc": "Comercial multicartera, asesor o agencia de marketing con cartera de clientes activa.",
    "role.2.economico_title": "MODELO ECONÓMICO",
    "role.2.economico_desc": "Canon anual de 3.000€. Comisión del 15% sobre honorarios netos.",
    "role.2.funciones_title": "TUS FUNCIONES PRINCIPALES",
    "role.2.f1": "Identificar leads cualificados.",
    "role.2.f2": "Realizar el discovery inicial.",
    "role.2.f3": "Cerrar convenios comerciales.",
    "role.2.ejemplo_title": "Ejemplo Real",
    "role.2.ejemplo_desc": "\"Caso Elena: Agencia de seguros que ofrece nuestros servicios como valor añadido a sus clientes pyme.\"",
    "role.3.title": "Delegado",
    "role.3.sub": "GESTIÓN",
    "role.3.desc": "Lidera una zona geográfica y coordina redes de Ejemplos de venta bajo nuestro modelo de franquicia.",
    "role.3.subtitle": "Lidera una zona geográfica exclusiva y coordina redes de Ejemplos de venta bajo nuestro modelo.",
    "role.3.perfil_title": "PERFIL IDEAL",
    "role.3.perfil_desc": "Emprendedor o ex-directivo con capacidad de gestión y liderazgo de equipos comerciales.",
    "role.3.economico_title": "MODELO ECONÓMICO",
    "role.3.economico_desc": "Canon de 12.000€/año. Comisión del 30% y control territorial.",
    "role.3.funciones_title": "TUS FUNCIONES PRINCIPALES",
    "role.3.f1": "Reclutar y formar Ejemplos de venta.",
    "role.3.f2": "Gestión estratégica territorial.",
    "role.3.f3": "Representación oficial de la marca.",
    "role.3.ejemplo_title": "Ejemplo Real",
    "role.3.ejemplo_desc": "\"Caso Manuel: Ex-director de banca que gestiona la provincia de Valencia con una red de 50 prescriptores.\"",
    "role.4.title": "Delegado",
    "role.4.sub": "OFICINA TÈCNICA",
    "role.4.desc": "El nivel más avanzado. Gestión comercial total y redacción de expedientes con IA de última generación.",
    "role.4.subtitle": "El nivel de control total. Gestión comercial y redacción técnica asistida por IA.",
    "role.4.perfil_title": "PERFIL IDEAL",
    "role.4.perfil_desc": "Consultoras establecidas o expertos en I+D que buscan maximizar rentabilidad.",
    "role.4.economico_title": "MODELO ECONÓMICO",
    "role.4.economico_desc": "Modelo de oficina técnica. Máxima comisión (hasta 40%) por control total.",
    "role.4.funciones_title": "TUS FUNCIONES PRINCIPALES",
    "role.4.f1": "Redacción técnica con IA propia.",
    "role.4.f2": "Validación técnica de expedientes.",
    "role.4.f3": "Gestión comercial premium.",
    "role.4.ejemplo_title": "Ejemplo Real",
    "role.4.ejemplo_desc": "\"Caso TechConsult: Consultoría que ha multiplicado por 10 su producción usando nuestra tecnología.\"",
    "portal.btn.info": "Saber más",
    "matcher.title": "Matcher de Carrera IA",
    "matcher.desc": "¿No sabes qué nivel elegir? Cuéntale a nuestra IA tu experiencia y te dirá cuál es tu rol ideal.",
    "matcher.btn": "Probar Matcher IA",
    "matcher.modal.title": "Asistente de Carrera",
    "matcher.modal.placeholder": "Ej: Soy comercial con 10 años de experiencia en banca y tengo muchos contactos en el sector industrial...",
    "matcher.modal.loading": "Analizando tu perfil...",
    "matcher.modal.btn": "Analizar mi Perfil",
    "matcher.modal.retry": "Probar de nuevo",
    "role.modal.title": "Detalles del Rol",
    "role.modal.close": "Entendido",
    "portal.module.1": "Módulo 1: Fundamentos",
    "portal.module.2": "Módulo 2: Tecnología",
    "portal.module.3": "Módulo 3: Comercial",
    "portal.module.4": "Módulo 4: Práctica",
    "portal.module.1.detail": "Aprende las bases de la financiación pública y nuestro modelo.",
    "portal.module.2.detail": "Domina las herramientas de IA que te permitirán ser 10 veces más productivo.",
    "portal.module.3.detail": "Técnicas de venta y discovery adaptadas a ayudas públicas.",
    "portal.module.4.detail": "Resolución de casos reales y puesta en marcha de tu actividad.",
    "portal.status.locked": "Bloqueado",
    "portal.status.done": "Completado",
    "portal.status.ready": "Listo para empezar",
    "portal.btn.start": "Empezar Módulo",
    "portal.btn.review": "Repasar",
    "module.passed": "¡Módulo Superado!",
    "module.retry": "Necesitas repasar",
    "module.score_msg": "Has acertado {score} de {total} preguntas.",
    "module.next": "Siguiente Módulo",
    "module.repeat": "Repetir Test",
    "module.confirm_btn": "Confirmar Respuesta",
    "welcome.title": "Bienvenido al Programa",
    "welcome.desc": "Estás a punto de iniciar una formación que cambiará tu trayectoria profesional.",
    "welcome.warning": "Este proceso requiere compromiso.",
    "welcome.btn": "Ir a mi Panel",
    "admin.roles.prescriptor": "Ejemplos de venta",
    "admin.roles.colaborador": "Colaborador",
    "admin.roles.delegado_g": "Delegado Gestión",
    "admin.roles.oficina_t": "Oficina Técnica",
    "admin.stats.total": "Candidatos",
    "admin.stats.pending": "Pendientes",
    "admin.stats.approved": "Aprovados",
    "admin.stats.interviews": "Entrevistas",
    "admin.overview.distribution": "Distribución por Roles",
    "admin.overview.recent": "Últimos Candidatos",
    "admin.overview.pending_tasks": "Tareas Urgente",
    "admin.overview.review_desc": "Tienes {count} CVs esperando validación para el nivel Colaborador.",
    "admin.overview.next_interviews": "Próximas Citas",
    "admin.nav.overview": "Resumen",
    "admin.nav.candidates": "Candidatos",
    "admin.nav.interviews": "Calendario",
    "admin.nav.settings": "Ajustes",
    "admin.search.placeholder": "Buscar por nombre o email...",
    "admin.table.candidate": "Candidato",
    "admin.table.role": "Rol",
    "admin.table.status": "Estado",
    "admin.table.progress": "Progreso",
    "admin.table.actions": "Acciones",
    "admin.status.review_cv": "Revisar CV",
    "admin.status.training": "En formación",
    "admin.btn.manage": "Gestionar",
    "admin.btn.schedule_new": "Programar Cita",
    "admin.calendar.title": "Calendario de Entrevistas",
    "admin.calendar.appointments": "Citas para hoy",
    "admin.calendar.empty": "Sin citas",
    "admin.modal.approve": "Aprobar Candidato",
    "admin.modal.discard": "Descartar",
    "admin.modal.schedule_title": "Programar Entrevista",
    "admin.modal.choose": "Seleccionar...",
    "admin.modal.date": "Fecha",
    "admin.modal.time": "Hora",
    "admin.modal.save": "Guardar Cita",
    "admin.modal.saving": "Guardando...",
    "admin.modal.cancel": "Cancelar",
    "admin.settings.tech_params": "Parámetros Técnicos",
    "admin.settings.cutoff": "Nota de Corte Test",
    "admin.settings.maintenance": "Modo Mantenimiento",
    "admin.settings.maintenance_desc": "Bloquea el acceso a candidatos.",
    "admin.settings.sim_guests": "Simulación de Invitados"
  },
  en: {
    "nav.home": "Home",
    "nav.login": "Login",
    "nav.register": "Join Now",
    "nav.logout": "Logout",
    "nav.continue": "Continue Training",
    "hero.tag": "REDESCOMERCIALES.AI",
    "hero.title": "Turn your partner network into an active and scalable sales channel",
    "hero.subtitle": "The AI-powered platform that identifies, motivates, and closes sales through your partners. Everything under your control in a single dashboard.",
    "hero.bullet1": "More sales without expanding internal team",
    "hero.bullet2": "Active and aligned partners",
    "hero.bullet3": "Full performance control",
    "hero.cta.primary": "Request free diagnosis",
    "hero.cta.secondary": "See how it works",
    "problem.headline": "Your commercial network exists… but it doesn't sell as it should",
    "problem.copy": "Most B2B companies have partners or distributors, but they are not activated, don't have clear incentives, and don't generate real pipeline.",
    "problem.remate": "Result: constant lost opportunity.",
    "problem.passive.title": "Passive Network (Current)",
    "problem.passive.item1.title": "The 'Ghost' Partner",
    "problem.passive.item1.desc": "Registered 6 months ago. 0 leads reported. No contact since onboarding.",
    "problem.passive.item2.title": "The 'Black Box'",
    "problem.passive.item2.desc": "You know they have clients, but you have no visibility into their pipeline until the sale is lost.",
    "problem.passive.item3.title": "Lack of Focus",
    "problem.passive.item3.desc": "Your partner prioritizes other products because they don't understand your value or how to sell it.",
    "problem.active.title": "Active Network (With us)",
    "problem.active.item1.title": "Proactive Activation",
    "problem.active.item1.desc": "Automatic alerts and continuous training. Partner reports 2-3 qualified leads per month.",
    "problem.active.item2.title": "Total Transparency",
    "problem.active.item2.desc": "Real-time dashboard. Partner sees their commissions and the status of each operation.",
    "problem.active.item3.title": "Co-selling Support",
    "problem.active.item3.desc": "Expert support from Redescomerciales.ai to help the partner close complex sales.",
    "solution.headline": "We activate your commercial network with methodology + technology",
    "solution.copy": "We are not an agency or a SaaS. We are a complete system to turn your network into sales.",
    "methodology.headline": "A proven system in 4 phases",
    "methodology.step1.title": "Phase 1 – Strategic Diagnosis",
    "methodology.step1.desc": "We analyze your current network, potential, and activation gaps.",
    "methodology.step2.title": "Phase 2 – Technological Adaptation",
    "methodology.step2.desc": "We implement a platform adapted to your network: activity tracking, incentives, and lead management.",
    "methodology.step3.title": "Phase 3 – Partner Recruitment",
    "methodology.step3.desc": "We design campaigns to attract new qualified partners.",
    "methodology.step4.title": "Phase 4 – Continuous Management and Activation",
    "methodology.step4.desc": "We operate your network to maximize results: monitoring, incentivization, and optimization.",
    "benefits.headline": "Results that directly impact your revenue",
    "benefits.item1.title": "Pipeline increase without increasing headcount",
    "benefits.item1.desc": "Multiply your business opportunities by leveraging external networks without the fixed costs of a large internal sales force.",
    "benefits.item2.title": "Real activation of dormant partners",
    "benefits.item2.desc": "We transform your database of inactive collaborators into a constant lead generation engine through incentives and follow-up.",
    "benefits.item3.title": "Greater commercial predictability",
    "benefits.item3.desc": "Get full visibility of the indirect pipeline with real-time data to make better strategic decisions.",
    "benefits.item4.title": "Scalable and measurable network",
    "benefits.item4.desc": "We design processes that allow growing without limits, maintaining the same quality and control in each new addition.",
    "benefits.item5.title": "Reduction of acquisition cost",
    "benefits.item5.desc": "Optimize your marketing and sales investment by paying only for real results and agreements closed by your network.",
    "diff.headline": "Why this is not just another agency or software",
    "diff.agencies.title": "Agencies",
    "diff.agencies.desc": "They generate leads but don't activate networks",
    "diff.saas.title": "SaaS",
    "diff.saas.desc": "They give you tools, but no execution",
    "diff.us.title": "Redescomerciales.ai",
    "diff.us.desc": "Complete system: strategy + technology + operation",
    "cases.headline": "Designed for companies that want to scale without increasing fixed costs",
    "cases.metric1.val": "+40%",
    "cases.metric1.label": "partner activation",
    "cases.metric2.val": "+250",
    "cases.metric2.label": "leads generated",
    "cases.metric3.val": "+$1.2M",
    "cases.metric3.label": "pipeline",
    "model.headline": "A model aligned with results",
    "model.copy": "We work with a hybrid model: initial setup, monthly management fee, and variable based on results.",
    "model.remate": "We win when you sell.",
    "faq.title": "Clearing doubts",
    "faq.q1": "Do I need to have a network already?",
    "faq.a1": "No, we also create it from scratch.",
    "faq.q2": "How long does it take to see results?",
    "faq.a2": "First indicators in weeks, real impact in months.",
    "faq.q3": "What type of companies fit?",
    "faq.a3": "B2B with a structured commercial cycle.",
    "faq.q4": "What does it involve internally?",
    "faq.a4": "Minimal dedication, we operate.",
    "cta.final.title": "Discover the real potential of your commercial network",
    "cta.final.subtitle": "We show you in a session how to activate your network and generate more sales without increasing structure.",
    "cta.final.btn": "Request strategic diagnosis",
    "support.marketing": "Marketing Support",
    "support.subject": "Subject",
    "support.inquiry": "Inquiry Details",
    "support.placeholder_subject": "How can we help you?",
    "support.placeholder_inquiry": "Describe your marketing needs in detail...",
    "support.send": "Send Inquiry",
    "support.success": "Inquiry sent successfully. Our team will contact you shortly.",
    "login.title": "Welcome back",
    "login.subtitle": "Access your management panel and continue your training.",
    "login.email": "Email Address",
    "login.email_placeholder": "you@email.com",
    "login.password": "Password",
    "login.pass_placeholder": "••••••••",
    "login.btn": "Enter Portal",
    "login.forgot": "Forgot your password?",
    "login.new": "New to Redescomerciales.ai?",
    "login.register_link": "Create professional account",
    "login.recovery_title": "Recover account",
    "login.recovery_subtitle": "We will send you a recovery link",
    "login.back": "Back",
    "login.recovery_success": "Email sent successfully",
    "login.recovery_error_email": "Please enter your email address",
    "register.title": "Create your account",
    "register.subtitle": "Join the leading platform in B2B channel activation.",
    "register.name": "Full Name",
    "register.name_placeholder": "Your name",
    "register.email": "Email",
    "register.email_placeholder": "you@email.com",
    "register.phone": "Phone",
    "register.phone_placeholder": "600 000 000",
    "register.level": "Desired level",
    "register.pass": "Password",
    "register.pass_placeholder": "••••••••",
    "register.pass_confirm": "Repeat password",
    "register.btn": "Create professional account",
    "register.existing": "Already have an account?",
    "register.login_link": "IDENTIFY HERE",
    "register.email_sent_title": "CHECK YOUR EMAIL!",
    "register.email_sent_desc": "We have sent a confirmation link to",
    "register.role.1": "1 - Prescriber",
    "register.role.2": "2 - Collaborator",
    "register.role.3": "3 - Delegate (Management)",
    "register.role.4": "4 - Delegate (Technical Office)",
    "portal.title": "Career Dashboard",
    "portal.subtitle": "Follow your professional itinerary.",
    "footer.rights": "Redescomerciales.ai - All rights reserved.",
    "ecosystem.title": "Our Ecosystem",
    "ecosystem.subtitle": "Four collaboration levels adapted to your profile.",
    "role.1.title": "Prescriber",
    "role.1.desc": "Recommend Redescomerciales.ai to your network and get passive benefits for each success.",
    "role.1.subtitle": "Ideal for senior professionals with a good network of contacts who want to generate extra income without operational burden.",
    "role.1.perfil_title": "IDEAL PROFILE",
    "role.1.perfil_desc": "Person who wants to monetize their contacts. Consultants or professionals from any sector.",
    "role.1.economico_title": "ECONOMIC MODEL",
    "role.1.economico_desc": "No entry cost (€0). You commission 7.5% on the closing of each agreement.",
    "role.1.funciones_title": "YOUR MAIN FUNCTIONS",
    "role.1.f1": "Identify contacts.",
    "role.1.f2": "Present the opportunity.",
    "role.1.f3": "Our team closes the sale.",
    "role.1.ejemplo_title": "Real Example",
    "role.1.ejemplo_desc": "\"Case Jorge (55 years old): Consultant who monetizes his old agenda by referring companies to Redescomerciales.ai without getting involved in management.\"",
    "role.2.title": "Collaborator",
    "role.2.desc": "Manage your own client portfolio and lead the commercial process with our technology.",
    "role.2.subtitle": "Ideal for consultants and sales reps who want to lead the sales process with their own technology.",
    "role.2.perfil_title": "IDEAL PROFILE",
    "role.2.perfil_desc": "Multi-portfolio commercial, advisor or marketing agency with active client portfolio.",
    "role.2.economico_title": "ECONOMIC MODEL",
    "role.2.economico_desc": "Annual fee of €3,000. 15% commission on net fees.",
    "role.2.funciones_title": "YOUR MAIN FUNCTIONS",
    "role.2.f1": "Identify qualified leads.",
    "role.2.f2": "Perform initial discovery.",
    "role.2.f3": "Close commercial agreements.",
    "role.2.ejemplo_title": "Real Example",
    "role.2.ejemplo_desc": "\"Case Elena: Insurance agency offering Redescomerciales.ai as a value-added service to its SME clients.\"",
    "role.3.title": "Delegate",
    "role.3.sub": "MANAGEMENT",
    "role.3.desc": "Lead a geographic area and coordinate prescriber networks under our franchise model.",
    "role.3.subtitle": "Lead an exclusive geographic area and coordinate prescriber networks under our model.",
    "role.3.perfil_title": "IDEAL PROFILE",
    "role.3.perfil_desc": "Entrepreneur or ex-executive with management and commercial team leadership capacity.",
    "role.3.economico_title": "ECONOMIC MODEL",
    "role.3.economico_desc": "Fee of €12,000/year. 30% commission and territorial control.",
    "role.3.funciones_title": "YOUR MAIN FUNCTIONS",
    "role.3.f1": "Recruit and train prescribers.",
    "role.3.f2": "Strategic territorial management.",
    "role.3.f3": "Official brand representation.",
    "role.3.ejemplo_title": "Real Example",
    "role.3.ejemplo_desc": "\"Case Manuel: Ex-bank director managing the province of Valencia with a network of 50 prescribers.\"",
    "role.4.title": "Delegate",
    "role.4.sub": "TECHNICAL OFFICE",
    "role.4.desc": "The most advanced level. Total commercial management and technical writing with next-gen AI.",
    "role.4.subtitle": "The level of total control. Commercial management and technical writing assisted by AI.",
    "role.4.perfil_title": "IDEAL PROFILE",
    "role.4.perfil_desc": "Established consultants or R&D experts looking to maximize profitability.",
    "role.4.economico_title": "ECONOMIC MODEL",
    "role.4.economico_desc": "Technical office model. Maximum commission (up to 40%) for total control.",
    "role.4.funciones_title": "YOUR MAIN FUNCTIONS",
    "role.4.f1": "Technical writing with own AI.",
    "role.4.f2": "Technical validation of files.",
    "role.4.f3": "Premium commercial management.",
    "role.4.ejemplo_title": "Real Example",
    "role.4.ejemplo_desc": "\"Case TechConsult: Consultancy that has 10x its production using Redescomerciales.ai.\"",
    "portal.btn.info": "Learn more",
    "matcher.title": "AI Career Matcher",
    "matcher.desc": "Don't know which level to choose? Tell our AI about your experience and it will find your ideal role.",
    "matcher.btn": "Try AI Matcher",
    "matcher.modal.title": "Career Assistant",
    "matcher.modal.placeholder": "E.g.: I am a sales rep with 10 years of experience in banking and I have many contacts in the industrial sector...",
    "matcher.modal.loading": "Analyzing your profile...",
    "matcher.modal.btn": "Analyze my Profile",
    "matcher.modal.retry": "Try again",
    "role.modal.title": "Role Details",
    "role.modal.close": "Understood",
    "portal.module.1": "Module 1: Fundamentals",
    "portal.module.2": "Module 2: Technology",
    "portal.module.3": "Module 3: Commercial",
    "portal.module.4": "Module 4: Practical",
    "portal.module.1.detail": "Learn the basics of public funding and the Redescomerciales.ai model.",
    "portal.module.2.detail": "Master the AI tools that will allow you to be 10x more productive.",
    "portal.module.3.detail": "Sales and discovery techniques adapted to public aid.",
    "portal.module.4.detail": "Resolution of real cases and starting your activity.",
    "portal.status.locked": "Locked",
    "portal.status.done": "Completed",
    "portal.status.ready": "Ready to start",
    "portal.btn.start": "Start Module",
    "portal.btn.review": "Review",
    "module.passed": "Module Passed!",
    "module.retry": "Need to review",
    "module.score_msg": "You got {score} out of {total} questions correct.",
    "module.next": "Next Module",
    "module.repeat": "Repeat Test",
    "module.confirm_btn": "Confirm Answer",
    "welcome.title": "Welcome to the Program",
    "welcome.desc": "You are about to start a training that will change your professional career.",
    "welcome.warning": "This process requires commitment.",
    "welcome.btn": "Go to Dashboard",
    "admin.roles.prescriptor": "Prescriber",
    "admin.roles.colaborador": "Collaborator",
    "admin.roles.delegado_g": "Management Delegate",
    "admin.roles.oficina_t": "Technical Office",
    "admin.stats.total": "Candidates",
    "admin.stats.pending": "Pending",
    "admin.stats.approved": "Approved",
    "admin.stats.interviews": "Interviews",
    "admin.overview.distribution": "Role Distribution",
    "admin.overview.recent": "Recent Candidates",
    "admin.overview.pending_tasks": "Urgent Tasks",
    "admin.overview.review_desc": "You have {count} CVs waiting for validation for the Collaborator level.",
    "admin.overview.next_interviews": "Next Appointments",
    "admin.nav.overview": "Overview",
    "admin.nav.candidates": "Candidates",
    "admin.nav.interviews": "Calendar",
    "admin.nav.settings": "Settings",
    "admin.search.placeholder": "Search by name or email...",
    "admin.table.candidate": "Candidate",
    "admin.table.role": "Role",
    "admin.table.status": "Status",
    "admin.table.progress": "Progress",
    "admin.table.actions": "Actions",
    "admin.status.review_cv": "Review CV",
    "admin.status.training": "Training",
    "admin.btn.manage": "Manage",
    "admin.btn.schedule_new": "Schedule Appt",
    "admin.calendar.title": "Interview Calendar",
    "admin.calendar.appointments": "Today's Appts",
    "admin.calendar.empty": "No appointments",
    "admin.modal.approve": "Approve Candidate",
    "admin.modal.discard": "Discard",
    "admin.modal.schedule_title": "Schedule Interview",
    "admin.modal.choose": "Select...",
    "admin.modal.date": "Date",
    "admin.modal.time": "Time",
    "admin.modal.save": "Save Appt",
    "admin.modal.saving": "Saving...",
    "admin.modal.cancel": "Cancel",
    "admin.settings.tech_params": "Technical Parameters",
    "admin.settings.cutoff": "Test Cutoff Score",
    "admin.settings.maintenance": "Maintenance Mode",
    "admin.settings.maintenance_desc": "Blocks candidate access.",
    "admin.settings.sim_guests": "Guest Simulation"
  },
  ca: {
    "nav.home": "Inici",
    "nav.login": "Iniciar Sessió",
    "nav.register": "Unir-se Ara",
    "nav.logout": "Sortir",
    "nav.continue": "Continuar Formació",
    "hero.tag": "PROGRAMA OFICIAL",
    "hero.title": "Uneix-te a l'Ecosistema Redescomerciales.ai",
    "hero.subtitle": "Descobreix una oportunitat real en un mercat de 400.000M€. Formem els líders del finançament públic del futur.",
    "hero.btn": "Unir-se Ara",
    "login.title": "Benvingut de nou",
    "login.subtitle": "Accedeix al teu panell de gestió i continua la teva formació.",
    "login.email": "Correu Electrònic",
    "login.email_placeholder": "tu@email.com",
    "login.password": "Contrasenya",
    "login.pass_placeholder": "••••••••",
    "login.btn": "Entrar al Portal",
    "login.forgot": "Has oblidat la contrasenya?",
    "login.new": "Nou a Redescomerciales.ai?",
    "login.register_link": "Crear compte professional",
    "login.recovery_title": "Recuperar compte",
    "login.recovery_subtitle": "T'enviarem un enllaç de recuperació",
    "login.back": "Tornar",
    "login.recovery_success": "Correu enviat correctament",
    "login.recovery_error_email": "Introdueix el teu correu electrònic",
    "register.title": "Crea el teu compte",
    "register.subtitle": "Uneix-te a l'ecosistema líder en gestió d'ajuts públics.",
    "register.name": "Nom Complet",
    "register.name_placeholder": "El teu nom",
    "register.email": "Email",
    "register.email_placeholder": "tu@email.com",
    "register.phone": "Telèfon",
    "register.phone_placeholder": "600 000 000",
    "register.level": "Nivell desitjat",
    "register.pass": "Contrasenya",
    "register.pass_placeholder": "••••••••",
    "register.pass_confirm": "Repetir contrasenya",
    "register.btn": "Crear compte professional",
    "register.existing": "Ja tens compte?",
    "register.login_link": "IDENTIFICA'T AQUÍ",
    "register.email_sent_title": "REVISA EL TEU CORREU!",
    "register.email_sent_desc": "Hem enviat un enllaç de confirmació a",
    "register.role.1": "1 - Ejemplos de venta",
    "register.role.2": "2 - Col·laborador",
    "register.role.3": "3 - Delegat (Gestió)",
    "register.role.4": "4 - Delegat (Oficina Tècnica)",
    "portal.title": "Panell de Carrera",
    "portal.subtitle": "Segueix el teu itinerari professional.",
    "footer.rights": "Líders en Finançament Públic. Tots els drets reservats.",
    "ecosystem.title": "El nostre Ecosistema",
    "ecosystem.subtitle": "Quatre nivells de col·laboració adaptats al teu perfil.",
    "role.1.title": "Ejemplos de venta",
    "role.1.desc": "Recomana Redescomerciales.ai a la teva xarxa de contactes i obté beneficis passius per cada èxit.",
    "role.1.subtitle": "Ideal per a professionals sènior amb una bona xarxa de contactes que volen generar ingressos extra.",
    "role.1.perfil_title": "PERFIL IDEAL",
    "role.1.perfil_desc": "Persona que vulgui monetitzar els seus contactes. Consultors o professionals de qualsevol sector.",
    "role.1.economico_title": "MODEL ECONÓMICO",
    "role.1.economico_desc": "Sense cost d'entrada (0€). Comisiones un 7,5% sobre el tancament de cada conveni.",
    "role.1.funciones_title": "LES TEVES FUNCIONS PRINCIPALS",
    "role.1.f1": "Identificar contactes.",
    "role.1.f2": "Presentar l'oportunitat.",
    "role.1.f3": "El nostre equip tanca la venda.",
    "role.1.ejemplo_title": "Exemple Real",
    "role.1.ejemplo_desc": "\"Cas Jorge (55 anys): Consultor que monetitza la seva antiga agenda referint empreses a Redescomerciales.ai.\"",
    "role.2.title": "Col·laborador",
    "role.2.desc": "Gestiona la teva pròpia cartera de clients i lidera el procés comercial amb la nostra tecnologia.",
    "role.2.subtitle": "Ideal per a consultors i comercials que volen liderar el procés de venda.",
    "role.2.perfil_title": "PERFIL IDEAL",
    "role.2.perfil_desc": "Comercial multicartera, assessor o agència de màrqueting amb cartera activa.",
    "role.2.economico_title": "MODEL ECONÓMICO",
    "role.2.economico_desc": "Cànon anual de 3.000€. Comissió del 15% sobre honoraris nets.",
    "role.2.funciones_title": "LES TEVES FUNCIONS PRINCIPALS",
    "role.2.f1": "Identificar leads qualificats.",
    "role.2.f2": "Realitzar el discovery inicial.",
    "role.2.f3": "Tancar convenis comercials.",
    "role.2.ejemplo_title": "Exemple Real",
    "role.2.ejemplo_desc": "\"Cas Elena: Agència d'assegurances que ofereix Redescomerciales.ai com a servei de valor afegit.\"",
    "role.3.title": "Delegat",
    "role.3.sub": "GESTIÓ",
    "role.3.desc": "Lidera una zona geogràfica i coordina xarxes de Ejemplos de venta sota el nostre model de franquícia.",
    "role.3.subtitle": "Lidera una zona geogràfica exclusiva i coordina xarxes de Ejemplos de venta.",
    "role.3.perfil_title": "PERFIL IDEAL",
    "role.3.perfil_desc": "Emprenedor o ex-directiu amb capacitat de gestió i lideratge d'equips.",
    "role.3.economico_title": "MODEL ECONÓMICO",
    "role.3.economico_desc": "Cànon de 12.000€/año. Comissió del 30% i control territorial.",
    "role.3.funciones_title": "LES TEVES FUNCIONS PRINCIPALS",
    "role.3.f1": "Reclutar i formar Ejemplos de venta.",
    "role.3.f2": "Gestió estratègica territorial.",
    "role.3.f3": "Representació oficial de la marca.",
    "role.3.ejemplo_title": "Exemple Real",
    "role.3.ejemplo_desc": "\"Cas Manuel: Ex-director de banca que gestiona la província de València.\"",
    "role.4.title": "Delegat",
    "role.4.sub": "OFICINA TÈCNICA",
    "role.4.desc": "El nivell més avanzado. Gestió comercial total i redaccío d'expedients amb IA d'última generació.",
    "role.4.subtitle": "El nivell de control total. Gestió comercial i redacció tècnica assistida por IA.",
    "role.4.perfil_title": "PERFIL IDEAL",
    "role.4.perfil_desc": "Consultores establertes o experts en R+D que busquen maximitzar rentabilitat.",
    "role.4.economico_title": "MODEL ECONÓMICO",
    "role.4.economico_desc": "Model d'oficina tècnica. Màxima comissió (fins al 40%) per control total.",
    "role.4.funciones_title": "LES TEVES FUNCIONS PRINCIPALS",
    "role.4.f1": "Redacción tècnica amb IA pròpia.",
    "role.4.f2": "Validació tècnica d'expedients.",
    "role.4.f3": "Gestió comercial premium.",
    "role.4.ejemplo_title": "Exemple Real",
    "role.4.ejemplo_desc": "\"Cas TechConsult: Consultoria que ha multiplicat per 10 la seva producció.\"",
    "portal.btn.info": "Saber-ne més",
    "matcher.title": "Matcher de Carrera IA",
    "matcher.desc": "No saps quin nivell triar? Explica a la nostra IA la teva experiència i et dirà quin és el teu rol ideal.",
    "matcher.btn": "Provar Matcher IA",
    "matcher.modal.title": "Assistent de Carrera",
    "matcher.modal.placeholder": "Ex: Sóc comercial amb 10 anys d'experiència en banca i tinc molts contactes...",
    "matcher.modal.loading": "Analitzant el teu perfil...",
    "matcher.modal.btn": "Analitzar el meu Perfil",
    "matcher.modal.retry": "Provar de nou",
    "role.modal.title": "Detalls del Rol",
    "role.modal.close": "Entès",
    "portal.module.1": "Mòdul 1: Fonaments",
    "portal.module.2": "Mòdul 2: Tecnologia",
    "portal.module.3": "Mòdul 3: Comercial",
    "portal.module.4": "Mòdul 4: Pràctica",
    "portal.module.1.detail": "Aprèn les bases del finançament públic i el model Redescomerciales.ai.",
    "portal.module.2.detail": "Domina les eines d'IA que et permetran ser 10 vegades més productiu.",
    "portal.module.3.detail": "Tècniques de venda i discovery adaptades a ajuts públics.",
    "portal.module.4.detail": "Resolució de casos reals i posada en marxa de la teva activitat.",
    "portal.status.locked": "Bloquejat",
    "portal.status.done": "Completat",
    "portal.status.ready": "Llest per començar",
    "portal.btn.start": "Començar Mòdul",
    "portal.btn.review": "Repassar",
    "module.passed": "Mòdul Superat!",
    "module.retry": "Necessites repassar",
    "module.score_msg": "Has encertat {score} de {total} preguntes.",
    "module.next": "Següent Mòdul",
    "module.repeat": "Repetir Test",
    "module.confirm_btn": "Confirmar Resposta",
    "welcome.title": "Benvingut al Programa",
    "welcome.desc": "Estàs a punt d'iniciar una formació que canviarà la teva trajectòria professional.",
    "welcome.warning": "Aquest procés requereix compromís.",
    "welcome.btn": "Anar al meu Panell",
    "admin.roles.prescriptor": "Ejemplos de venta",
    "admin.roles.colaborador": "Col·laborador",
    "admin.roles.delegado_g": "Delegat Gestió",
    "admin.roles.oficina_t": "Oficina Tècnica",
    "admin.stats.total": "Candidats",
    "admin.stats.pending": "Pendents",
    "admin.stats.approved": "Aprovats",
    "admin.stats.interviews": "Entrevistes",
    "admin.overview.distribution": "Distribució per Rols",
    "admin.overview.recent": "Últims Candidatos",
    "admin.overview.pending_tasks": "Tasques Urgent",
    "admin.overview.review_desc": "Tens {count} CV esperant validació per al nivell Col·laborador.",
    "admin.overview.next_interviews": "Properes Cites",
    "admin.nav.overview": "Resum",
    "admin.nav.candidates": "Candidats",
    "admin.nav.interviews": "Calendari",
    "admin.nav.settings": "Ajustos",
    "admin.search.placeholder": "Cercar per nom o email...",
    "admin.table.candidate": "Candidat",
    "admin.table.role": "Rol",
    "admin.table.status": "Estat",
    "admin.table.progress": "Progrés",
    "admin.table.actions": "Accions",
    "admin.status.review_cv": "Revisar CV",
    "admin.status.training": "En formació",
    "admin.btn.manage": "Gestionar",
    "admin.btn.schedule_new": "Programar Cita",
    "admin.calendar.title": "Calendari d'Entrevistes",
    "admin.calendar.appointments": "Cites per avui",
    "admin.calendar.empty": "Sense cites",
    "admin.modal.approve": "Aprovar Candidat",
    "admin.modal.discard": "Descartar",
    "admin.modal.schedule_title": "Programar Entrevista",
    "admin.modal.choose": "Seleccionar...",
    "admin.modal.date": "Data",
    "admin.modal.time": "Hora",
    "admin.modal.save": "Guardar Cita",
    "admin.modal.saving": "Guardant...",
    "admin.modal.cancel": "Cancel·lar",
    "admin.settings.tech_params": "Paràmetres Tècnics",
    "admin.settings.cutoff": "Nota de Tall Test",
    "admin.settings.maintenance": "Mode Manteniment",
    "admin.settings.maintenance_desc": "Bloqueja l'accés a candidats.",
    "admin.settings.sim_guests": "Simulació de Convidats"
  },
  fr: {
    "nav.home": "Accueil",
    "nav.login": "Connexion",
    "nav.register": "S'inscrire",
    "nav.logout": "Déconnexion",
    "nav.continue": "Continuer Formation",
    "hero.tag": "PROGRAMME OFFICIEL",
    "hero.title": "Rejoignez l'écosystème Redescomerciales.ai",
    "hero.subtitle": "Découvrez une réelle opportunité sur un marché de 400 milliards d'euros. Nous formons les leaders du financement public.",
    "hero.btn": "Rejoindre",
    "login.title": "Bon retour parmi nous",
    "login.subtitle": "Accédez à votre espace de gestion et continuez votre formation.",
    "login.email": "Adresse E-mail",
    "login.email_placeholder": "votre@email.com",
    "login.password": "Mot de passe",
    "login.pass_placeholder": "••••••••",
    "login.btn": "Entrer au Portail",
    "login.forgot": "Mot de passe oublié ?",
    "login.new": "Nouveau sur Redescomerciales.ai ?",
    "login.register_link": "Créer un compte professionnel",
    "login.recovery_title": "Récupérer le compte",
    "login.recovery_subtitle": "Nous vous enverrons un lien de récupération",
    "login.back": "Retour",
    "login.recovery_success": "E-mail envoyé avec succès",
    "login.recovery_error_email": "Veuillez entrer votre e-mail",
    "register.title": "Créez votre compte",
    "register.subtitle": "Rejoignez l'écosystème leader en gestion d'aides publiques.",
    "register.name": "Nom complet",
    "register.name_placeholder": "Votre nom",
    "register.email": "E-mail",
    "register.email_placeholder": "votre@email.com",
    "register.phone": "Téléphone",
    "register.phone_placeholder": "0600000000",
    "register.level": "Niveau souhaité",
    "register.pass": "Mot de passe",
    "register.pass_placeholder": "••••••••",
    "register.pass_confirm": "Répéter le mot de passe",
    "register.btn": "Créer un compte professionnel",
    "register.existing": "Vous avez déjà un compte ?",
    "register.login_link": "IDENTIFIEZ-VOUS ICI",
    "register.email_sent_title": "VÉRIFIEZ VOS E-MAILS !",
    "register.email_sent_desc": "Nous avons envoyé un lien de confirmation à",
    "register.role.1": "1 - Prescripteur",
    "register.role.2": "2 - Collaborateur",
    "register.role.3": "3 - Délégué (Gestion)",
    "register.role.4": "4 - Délégué (Bureau Technique)",
    "portal.title": "Tableau de Bord",
    "portal.subtitle": "Suivez votre parcours professionnel.",
    "footer.rights": "Leaders en financement public. Tous droits réservés.",
    "ecosystem.title": "Notre Écosystème",
    "ecosystem.subtitle": "Quatre niveaux de collaboration adaptés à votre profil.",
    "role.1.title": "Prescripteur",
    "role.1.desc": "Recommandez Redescomerciales.ai à votre réseau et obtenez des avantages passifs pour chaque succès.",
    "role.1.subtitle": "Idéal pour les professionnels seniors ayant un bon réseau qui souhaitent générer des revenus extra.",
    "role.1.perfil_title": "PROFIL IDÉAL",
    "role.1.perfil_desc": "Personne souhaitant monétiser ses contacts. Consultants ou professionnels de tout secteur.",
    "role.1.economico_title": "MODÈLE ÉCONOMIQUE",
    "role.1.economico_desc": "Pas de coût d'entrée (0€). Commission de 7,5% sur la clôture de chaque convention.",
    "role.1.funciones_title": "VOS MISSIONS PRINCIPALES",
    "role.1.f1": "Identifier les contacts.",
    "role.1.f2": "Présenter l'opportunité.",
    "role.1.f3": "Notre équipe conclut la vente.",
    "role.1.ejemplo_title": "Exemple concret",
    "role.1.ejemplo_desc": "\"Cas Jorge (55 ans) : Consultant qui monétise son carnet d'adresses en recommandant Redescomerciales.ai.\"",
    "role.2.title": "Collaborateur",
    "role.2.desc": "Gérez votre propre portefeuille de clients et dirigez le processus commercial avec notre technologie.",
    "role.2.subtitle": "Idéal pour les consultants et commerciaux qui souhaitent diriger le processus de vente.",
    "role.2.perfil_title": "PROFIL IDÉAL",
    "role.2.perfil_desc": "Commercial multi-portefeuille, conseiller ou agence avec un portefeuille de clients actifs.",
    "role.2.economico_title": "MODÈLE ÉCONOMIQUE",
    "role.2.economico_desc": "Redevance annuelle de 3 000€. Commission de 15% sur les honoraires nets.",
    "role.2.funciones_title": "VOS MISSIONS PRINCIPALES",
    "role.2.f1": "Identifier les leads qualifiés.",
    "role.2.f2": "Réaliser le discovery initial.",
    "role.2.f3": "Conclure les accords commerciaux.",
    "role.2.ejemplo_title": "Exemple concret",
    "role.2.ejemplo_desc": "\"Cas Elena : Agence d'assurance offrant Redescomerciales.ai comme service à valeur ajoutée.\"",
    "role.3.title": "Délégué",
    "role.3.sub": "GESTION",
    "role.3.desc": "Dirigez une zone géographique et coordonnez des réseaux de prescripteurs sous notre modèle.",
    "role.3.subtitle": "Dirigez une zone géographique exclusive et coordonnez des prescripteurs.",
    "role.3.perfil_title": "PROFIL IDÉAL",
    "role.3.perfil_desc": "Entrepreneur ou ex-dirigeant avec capacité de gestion et de leadership d'équipe.",
    "role.3.economico_title": "MODÈLE ÉCONOMIQUE",
    "role.3.economico_desc": "Redevance de 12 000€/an. Commission de 30% et contrôle territorial.",
    "role.3.funciones_title": "VOS MISSIONS PRINCIPALES",
    "role.3.f1": "Recruter et former les prescripteurs.",
    "role.3.f2": "Gestion stratégique territoriale.",
    "role.3.f3": "Représentation officielle de la marque.",
    "role.3.ejemplo_title": "Exemple concret",
    "role.3.ejemplo_desc": "\"Cas Manuel : Ancien directeur de banque gérant une région avec 50 prescripteurs.\"",
    "role.4.title": "Délégué",
    "role.4.sub": "BUREAU TECHNIQUE",
    "role.4.desc": "Le niveau le plus avancé. Gestion commerciale totale et rédaction de dossiers avec IA.",
    "role.4.subtitle": "Contrôle total. Gestion commerciale et rédaction technique assistée par IA.",
    "role.4.perfil_title": "PROFIL IDÉAL",
    "role.4.perfil_desc": "Cabinets établis ou experts en R&D cherchant à maximiser la rentabilité.",
    "role.4.economico_title": "MODÈLE ÉCONOMIQUE",
    "role.4.economico_desc": "Modèle bureau technique. Commission maximale (jusqu'à 40%).",
    "role.4.funciones_title": "VOS MISSIONS PRINCIPALES",
    "role.4.f1": "Rédaction technique avec IA propre.",
    "role.4.f2": "Validation technique des dossiers.",
    "role.4.f3": "Gestion commerciale premium.",
    "role.4.ejemplo_title": "Exemple concret",
    "role.4.ejemplo_desc": "\"Cas TechConsult : Cabinet ayant décuplé sa production grâce à Redescomerciales.ai.\"",
    "portal.btn.info": "En savoir plus",
    "matcher.title": "Matcher de carrière IA",
    "matcher.desc": "Vous ne savez pas quel niveau choisir ? Décrivez votre expérience à notre IA pour trouver votre rôle idéal.",
    "matcher.btn": "Tester le Matcher IA",
    "matcher.modal.title": "Assistant Carrière",
    "matcher.modal.placeholder": "Ex : Je suis commercial avec 10 ans d'expérience dans la banque...",
    "matcher.modal.loading": "Analyse de votre profil...",
    "matcher.modal.btn": "Analyser mon profil",
    "matcher.modal.retry": "Réessayer",
    "role.modal.title": "Détails du rôle",
    "role.modal.close": "Compris",
    "portal.module.1": "Module 1 : Fondamentaux",
    "portal.module.2": "Module 2 : Technologie",
    "portal.module.3": "Module 3 : Commercial",
    "portal.module.4": "Module 4 : Pratique",
    "portal.module.1.detail": "Apprenez les bases du financement public et du modèle Redescomerciales.ai.",
    "portal.module.2.detail": "Maîtrisez les outils d'IA qui vous permettront d'être 10 fois plus productif.",
    "portal.module.3.detail": "Techniques de vente et discovery adaptées aux aides publiques.",
    "portal.module.4.detail": "Résolution de cas réels et lancement de votre activité.",
    "portal.status.locked": "Verrouillé",
    "portal.status.done": "Terminé",
    "portal.status.ready": "Prêt à commencer",
    "portal.btn.start": "Démarrer Module",
    "portal.btn.review": "Réviser",
    "module.passed": "Module réussi !",
    "module.retry": "Besoin de réviser",
    "module.score_msg": "Vous avez réussi {score} sur {total} questions.",
    "module.next": "Module suivant",
    "module.repeat": "Répéter le test",
    "module.confirm_btn": "Confirmer",
    "welcome.title": "Bienvenue au programme",
    "welcome.desc": "Vous allez commencer une formation qui changera votre carrière professionnelle.",
    "welcome.warning": "Ce processus demande de l'engagement.",
    "welcome.btn": "Aller à mon panel",
    "admin.roles.prescriptor": "Prescripteur",
    "admin.roles.colaborador": "Collaborateur",
    "admin.roles.delegado_g": "Délégué Gestion",
    "admin.roles.oficina_t": "Bureau Technique",
    "admin.stats.total": "Candidats",
    "admin.stats.pending": "En attente",
    "admin.stats.approved": "Approuvés",
    "admin.stats.interviews": "Entretiens",
    "admin.overview.distribution": "Répartition des rôles",
    "admin.overview.recent": "Derniers candidats",
    "admin.overview.pending_tasks": "Tâches urgentes",
    "admin.overview.review_desc": "Vous avez {count} CV en attente de validation.",
    "admin.overview.next_interviews": "Prochains rendez-vous",
    "admin.nav.overview": "Résumé",
    "admin.nav.candidates": "Candidats",
    "admin.nav.interviews": "Calendrier",
    "admin.nav.settings": "Réglages",
    "admin.search.placeholder": "Chercher par nom ou e-mail...",
    "admin.table.candidate": "Candidat",
    "admin.table.role": "Rôle",
    "admin.table.status": "Statut",
    "admin.table.progress": "Progrès",
    "admin.table.actions": "Actions",
    "admin.status.review_cv": "Réviser CV",
    "admin.status.training": "En formation",
    "admin.btn.manage": "Gérer",
    "admin.btn.schedule_new": "Programmer RDV",
    "admin.calendar.title": "Calendrier des entretiens",
    "admin.calendar.appointments": "RDV du jour",
    "admin.calendar.empty": "Pas de rendez-vous",
    "admin.modal.approve": "Approuver candidat",
    "admin.modal.discard": "Rejeter",
    "admin.modal.schedule_title": "Programmer entretien",
    "admin.modal.choose": "Sélectionner...",
    "admin.modal.date": "Date",
    "admin.modal.time": "Heure",
    "admin.modal.save": "Sauvegarder",
    "admin.modal.saving": "Enregistrement...",
    "admin.modal.cancel": "Annuler",
    "admin.settings.tech_params": "Paramètres techniques",
    "admin.settings.cutoff": "Note de coupure test",
    "admin.settings.maintenance": "Mode maintenance",
    "admin.settings.maintenance_desc": "Bloque l'accès aux candidats.",
    "admin.settings.sim_guests": "Simulation d'invités"
  },
  de: {
    "nav.home": "Startseite",
    "nav.login": "Anmelden",
    "nav.register": "Jetzt beitreten",
    "nav.logout": "Abmelden",
    "nav.continue": "Schulung fortsetzen",
    "hero.tag": "OFFIZIELLES PROGRAMM",
    "hero.title": "Werden Sie Teil des Redescomerciales.ai-Ökosystems",
    "hero.subtitle": "Entdecken Sie eine echte Chance in einem 400-Mrd.-€-Markt. Wir bilden die Führungskräfte der öffentlichen Finanzierung von morgen aus.",
    "hero.btn": "Jetzt beitreten",
    "login.title": "Willkommen zurück",
    "login.subtitle": "Greifen Sie auf Ihr Dashboard zu und setzen Sie Ihre Schulung fort.",
    "login.email": "E-Mail-Adresse",
    "login.email_placeholder": "ihre@email.com",
    "login.password": "Passwort",
    "login.pass_placeholder": "••••••••",
    "login.btn": "Portal betreten",
    "login.forgot": "Passwort vergessen?",
    "login.new": "Neu bei Redescomerciales.ai?",
    "login.register_link": "Professionelles Konto erstellen",
    "login.recovery_title": "Konto wiederherstellen",
    "login.recovery_subtitle": "Wir senden Ihnen einen Link zur Wiederherstellung",
    "login.back": "Zurück",
    "login.recovery_success": "E-Mail erfolgreich gesendet",
    "login.recovery_error_email": "Bitte geben Sie Ihre E-Mail-Adresse ein",
    "register.title": "Konto erstellen",
    "register.subtitle": "Treten Sie dem führenden Ökosystem für Fördermittelmanagement bei.",
    "register.name": "Vollständiger Name",
    "register.name_placeholder": "Ihr Name",
    "register.email": "E-Mail",
    "register.email_placeholder": "ihre@email.com",
    "register.phone": "Telefon",
    "register.phone_placeholder": "0123 456789",
    "register.level": "Gewünschtes Level",
    "register.pass": "Passwort",
    "register.pass_placeholder": "••••••••",
    "register.pass_confirm": "Passwort wiederholen",
    "register.btn": "Professionelles Konto erstellen",
    "register.existing": "Bereits ein Konto?",
    "register.login_link": "HIER ANMELDEN",
    "register.email_sent_title": "POSTFACH PRÜFEN!",
    "register.email_sent_desc": "Wir haben einen Bestätigungslink gesendet an",
    "register.role.1": "1 - Empfehlungsgeber",
    "register.role.2": "2 - Kooperationspartner",
    "register.role.3": "3 - Delegierter (Management)",
    "register.role.4": "4 - Delegierter (Technisches Büro)",
    "portal.title": "Karriere-Dashboard",
    "portal.subtitle": "Verfolgen Sie Ihren beruflichen Weg.",
    "footer.rights": "Führend in der öffentlichen Finanzierung. Alle Rechte vorbehalten.",
    "ecosystem.title": "Unser Ökosystem",
    "ecosystem.subtitle": "Vier Kooperationsebenen, angepasst an Ihr Pfrofil.",
    "role.1.title": "Empfehlungsgeber",
    "role.1.desc": "Empfehlen Sie Redescomerciales.ai Ihrem Netzwerk und verdienen Sie passiv an jedem Erfolg.",
    "role.1.subtitle": "Ideal für erfahrene Profis mit gutem Netzwerk, die Zusatzeinkommen ohne operativen Aufwand suchen.",
    "role.1.perfil_title": "IDEALES PROFIL",
    "role.1.perfil_desc": "Personen, die Kontakte monetarisieren möchten. Berater oder Profis aus allen Sektoren.",
    "role.1.economico_title": "WIRTSCHAFTSMODELL",
    "role.1.economico_desc": "Keine Einstiegskosten (0€). 7,5% Provision pro abgeschlossenem Vertrag.",
    "role.1.funciones_title": "IHRE HAUPTAUFGABEN",
    "role.1.f1": "Kontakte identifizieren.",
    "role.1.f2": "Die Chance präsentieren.",
    "role.1.f3": "Unser Team schließt den Verkauf ab.",
    "role.1.ejemplo_title": "Realbeispiel",
    "role.1.ejemplo_desc": "\"Fall Jorge (55): Berater, der sein altes Netzwerk durch Empfehlungen monetarisiert.\"",
    "role.2.title": "Kooperationspartner",
    "role.2.desc": "Verwalten Sie Ihr eigenes Portfolio und leiten Sie den Vertrieb mit unserer Technologie.",
    "role.2.subtitle": "Ideal für Berater and Vertriebler, die den Verkaufsprozess selbst steuern möchten.",
    "role.2.perfil_title": "IDEALES PROFIL",
    "role.2.perfil_desc": "Mehrfachvertreter, Berater oder Agentur mit aktivem Kundenstamm.",
    "role.2.economico_title": "WIRTSCHAFTSMODELL",
    "role.2.economico_desc": "Jahresgebühr von 3.000€. 15% Provision auf Nettohonorare.",
    "role.2.funciones_title": "IHRE HAUPTAUFGABEN",
    "role.2.f1": "Qualifizierte Leads finden.",
    "role.2.f2": "Erstes Discovery-Gespräch.",
    "role.2.f3": "Verträge abschließen.",
    "role.2.ejemplo_title": "Realbeispiel",
    "role.2.ejemplo_desc": "\"Fall Elena: Versicherungsagentur, die Redescomerciales.ai als Mehrwertdienst anbietet.\"",
    "role.3.title": "Delegierter",
    "role.3.sub": "MANAGEMENT",
    "role.3.desc": "Leiten Sie eine Region und koordinieren Sie Netzwerke unter unserem Franchise-Modell.",
    "role.3.subtitle": "Exklusive Gebietsleitung und Koordination von Empfehlungsgebern.",
    "role.3.perfil_title": "IDEALES PROFIL",
    "role.3.perfil_desc": "Unternehmer oder Ex-Führungskräfte mit Management-Erfahrung.",
    "role.3.economico_title": "WIRTSCHAFTSMODELL",
    "role.3.economico_desc": "Gebühr von 12.000€/Jahr. 30% Provision und Gebietskontrolle.",
    "role.3.funciones_title": "IHRE HAUPTAUFGABEN",
    "role.3.f1": "Partner rekrutieren & schulen.",
    "role.3.f2": "Strategisches Gebietsmanagement.",
    "role.3.f3": "Offizielle Markenrepräsentanz.",
    "role.3.ejemplo_title": "Realbeispiel",
    "role.3.ejemplo_desc": "\"Fall Manuel: Ex-Bankdirektor, der eine ganze Provinz mit 50 Partnern leitet.\"",
    "role.4.title": "Delegierter",
    "role.4.sub": "TECHNISCHES BÜRO",
    "role.4.desc": "Das fortgeschrittenste Level. Vollständiges Management und Projekterstellung mit KI.",
    "role.4.subtitle": "Volle Kontrolle. Vertrieb und technische Erstellung unterstützt durch KI.",
    "role.4.perfil_title": "IDEALES PROFIL",
    "role.4.perfil_desc": "Etablierte Berater oder F&E-Experten, die Rentabilität maximieren möchten.",
    "role.4.economico_title": "WIRTSCHAFTSMODELL",
    "role.4.economico_desc": "Technisches Büro Modell. Maximale Provision (bis zu 40%).",
    "role.4.funciones_title": "IHRE HAUPTAUFGABEN",
    "role.4.f1": "Technische Erstellung mit eigener KI.",
    "role.4.f2": "Technische Validierung von Dossiers.",
    "role.4.f3": "Premium-Vertriebsmanagement.",
    "role.4.ejemplo_title": "Realbeispiel",
    "role.4.ejemplo_desc": "\"Fall TechConsult: Beratung, die ihre Produktion verzehnfacht hat.\"",
    "portal.btn.info": "Mehr erfahren",
    "matcher.title": "KI-Karriere-Matcher",
    "matcher.desc": "Unsicher, welches Level passt? Erzählen Sie unserer KI von Ihrer Erfahrung.",
    "matcher.btn": "KI Matcher testen",
    "matcher.modal.title": "Karriere-Assistent",
    "matcher.modal.placeholder": "Z.B.: Ich bin Vertriebler mit 10 Jahren Bankerfahrung...",
    "matcher.modal.loading": "Profil wird analysiert...",
    "matcher.modal.btn": "Mein Profil analysieren",
    "matcher.modal.retry": "Erneut versuchen",
    "role.modal.title": "Rollendetails",
    "role.modal.close": "Verstanden",
    "portal.module.1": "Modul 1: Grundlagen",
    "portal.module.2": "Modul 2: Technologie",
    "portal.module.3": "Modul 3: Vertrieb",
    "portal.module.4": "Modul 4: Praxis",
    "portal.module.1.detail": "Lernen Sie die Grundlagen der öffentlichen Finanzierung und das Redescomerciales.ai-Modell kennen.",
    "portal.module.2.detail": "Meistern Sie die KI-Tools, die Sie 10-mal produktiver machen.",
    "portal.module.3.detail": "Vertriebstechniken angepasst an Fördermittel.",
    "portal.module.4.detail": "Lösung realer Fälle und Start Ihrer Aktivität.",
    "portal.status.locked": "Gesperrt",
    "portal.status.done": "Abgeschlossen",
    "portal.status.ready": "Bereit zum Start",
    "portal.btn.start": "Modul starten",
    "portal.btn.review": "Wiederholen",
    "module.passed": "Modul bestanden!",
    "module.retry": "Wiederholung nötig",
    "module.score_msg": "Sie haben {score} von {total} Fragen richtig beantwortet.",
    "module.next": "Nächstes Modul",
    "module.repeat": "Test wiederholen",
    "module.confirm_btn": "Antwort bestätigen",
    "welcome.title": "Willkommen im Programm",
    "welcome.desc": "Sie starten eine Ausbildung, die Ihre Karriere verändern wird.",
    "welcome.warning": "Dieser Prozess erfordert Engagement.",
    "welcome.btn": "Zu meinem Dashboard",
    "admin.roles.prescriptor": "Empfehlungsgeber",
    "admin.roles.colaborador": "Partner",
    "admin.roles.delegado_g": "Delegierter Management",
    "admin.roles.oficina_t": "Technisches Büro",
    "admin.stats.total": "Kandidaten",
    "admin.stats.pending": "Ausstehend",
    "admin.stats.approved": "Bestätigt",
    "admin.stats.interviews": "Interviews",
    "admin.overview.distribution": "Rollenverteilung",
    "admin.overview.recent": "Neueste Kandidaten",
    "admin.overview.pending_tasks": "Dringende Aufgaben",
    "admin.overview.review_desc": "Sie haben {count} CVs zur Überprüfung.",
    "admin.overview.next_interviews": "Nächste Termine",
    "admin.nav.overview": "Übersicht",
    "admin.nav.candidates": "Kandidaten",
    "admin.nav.interviews": "Kalender",
    "admin.nav.settings": "Einstellungen",
    "admin.search.placeholder": "Nach Name oder E-Mail suchen...",
    "admin.table.candidate": "Kandidat",
    "admin.table.role": "Rolle",
    "admin.table.status": "Status",
    "admin.table.progress": "Fortschritt",
    "admin.table.actions": "Aktionen",
    "admin.status.review_cv": "CV prüfen",
    "admin.status.training": "In Schulung",
    "admin.btn.manage": "Verwalten",
    "admin.btn.schedule_new": "Termin planen",
    "admin.calendar.title": "Interview-Kalender",
    "admin.calendar.appointments": "Heutige Termine",
    "admin.calendar.empty": "Keine Termine",
    "admin.modal.approve": "Kandidat bestätigen",
    "admin.modal.discard": "Ablehnen",
    "admin.modal.schedule_title": "Interview planen",
    "admin.modal.choose": "Auswählen...",
    "admin.modal.date": "Datum",
    "admin.modal.time": "Uhrzeit",
    "admin.modal.save": "Termin speichern",
    "admin.modal.saving": "Speichern...",
    "admin.modal.cancel": "Abbrechen",
    "admin.settings.tech_params": "Technische Parameter",
    "admin.settings.cutoff": "Bestehensgrenze",
    "admin.settings.maintenance": "Wartungsmodus",
    "admin.settings.maintenance_desc": "Blockiert Kandidatenzugang.",
    "admin.settings.sim_guests": "Gast-Simulation"
  },
  it: {
    "nav.home": "Home",
    "nav.login": "Accedi",
    "nav.register": "Unisciti Ora",
    "nav.logout": "Esci",
    "nav.continue": "Continua Formazione",
    "hero.tag": "PROGRAMMA UFFICIALE",
    "hero.title": "Unisciti all'Ecosistema Redescomerciales.ai",
    "hero.subtitle": "Scopri un'opportunità reale in un mercato da 400 miliardi di euro. Formiamo i leader del finanziamento pubblico.",
    "hero.btn": "Unisciti Ora",
    "login.title": "Bentornato",
    "login.subtitle": "Accedi al tuo pannello e continua la tua formazione.",
    "login.email": "Indirizzo E-mail",
    "login.email_placeholder": "tua@email.com",
    "login.password": "Password",
    "login.pass_placeholder": "••••••••",
    "login.btn": "Entra nel Portale",
    "login.forgot": "Password dimenticata?",
    "login.new": "Nuovo su Redescomerciales.ai?",
    "login.register_link": "Crea un account professionale",
    "login.recovery_title": "Recupera account",
    "login.recovery_subtitle": "Ti invieremo un link di recupero",
    "login.back": "Indietro",
    "login.recovery_success": "E-mail inviata con successo",
    "login.recovery_error_email": "Inserisci la tua e-mail",
    "register.title": "Crea il tuo account",
    "register.subtitle": "Unisciti all'ecosistema leader nella gestione di aiuti pubblici.",
    "register.name": "Nome Completo",
    "register.name_placeholder": "Il tuo nome",
    "register.email": "E-mail",
    "register.email_placeholder": "tua@email.com",
    "register.phone": "Telefono",
    "register.phone_placeholder": "02 0000000",
    "register.level": "Livello desiderato",
    "register.pass": "Password",
    "register.pass_placeholder": "••••••••",
    "register.pass_confirm": "Ripeti password",
    "register.btn": "Crea account professionale",
    "register.existing": "Hai già un account?",
    "register.login_link": "ACCEDI QUI",
    "register.email_sent_title": "CONTROLLA L'E-MAIL!",
    "register.email_sent_desc": "Abbiamo inviato un link di conferma a",
    "register.role.1": "1 - Segnalatore",
    "register.role.2": "2 - Collaboratore",
    "register.role.3": "3 - Delegato (Gestione)",
    "register.role.4": "4 - Delegato (Ufficio Tecnico)",
    "portal.title": "Dashboard di Carriera",
    "portal.subtitle": "Segui il tuo percorso professionale.",
    "footer.rights": "Leader nel finanziamento pubblico. Tutti i diritti riservati.",
    "ecosystem.title": "Il Nostro Ecosistema",
    "ecosystem.subtitle": "Quattro livelli di collaborazione adatti al tuo profilo.",
    "role.1.title": "Segnalatore",
    "role.1.desc": "Raccomanda Redescomerciales.ai alla tua rete e ottieni vantaggi passivi per ogni successo.",
    "role.1.subtitle": "Ideale per professionisti senior con una buona rete di contatti che vogliono generare entrate extra.",
    "role.1.perfil_title": "PROFILO IDEALE",
    "role.1.perfil_desc": "Persona che vuole monetizzare i propri contatti. Consulenti o professionisti di ogni settore.",
    "role.1.economico_title": "MODELLO ECONOMICO",
    "role.1.economico_desc": "Senza costi d'ingresso (0€). Commissione del 7,5% sulla chiusura di ogni contratto.",
    "role.1.funciones_title": "LE TUE FUNZIONI PRINCIPALI",
    "role.1.f1": "Identificare contatti.",
    "role.1.f2": "Presentare l'opportunità.",
    "role.1.f3": "Il nostro team chiude la vendita.",
    "role.1.ejemplo_title": "Esempio Reale",
    "role.1.ejemplo_desc": "\"Caso Jorge (55 anni): Consulente che monetizza la sua vecchia agenda raccomandando Redescomerciales.ai.\"",
    "role.2.title": "Collaboratore",
    "role.2.desc": "Gestisci il tuo portafoglio clienti e guida il processo commerciale con la nuestra tecnologia.",
    "role.2.subtitle": "Ideale per consulenti e venditori che vogliono guidare il processo di vendita.",
    "role.2.perfil_title": "PROFILO IDEALE",
    "role.2.perfil_desc": "Venditore multi-portafoglio, consulente o agenzia con portafoglio clienti attivo.",
    "role.2.economico_title": "MODELLO ECONOMICO",
    "role.2.economico_desc": "Canone annuale di 3.000€. Commissione del 15% sugli onorari netti.",
    "role.2.funciones_title": "LE TUE FUNZIONI PRINCIPALES",
    "role.2.f1": "Identificare lead qualificati.",
    "role.2.f2": "Effettuare il discovery iniziale.",
    "role.2.f3": "Chiudere accordi commerciali.",
    "role.2.ejemplo_title": "Esempio Reale",
    "role.2.ejemplo_desc": "\"Caso Elena: Agenzia assicurativa che offre Redescomerciales.ai como servizio a valore aggiunto.\"",
    "role.3.title": "Delegato",
    "role.3.sub": "GESTIONE",
    "role.3.desc": "Guida un'area geografica e coordina reti di segnalatori sotto il nostro modello.",
    "role.3.subtitle": "Guida un'area esclusiva e coordina reti di segnalatori.",
    "role.3.perfil_title": "PROFILO IDEAL",
    "role.3.perfil_desc": "Imprenditore o ex-dirigente con capacità de gestione e leadership.",
    "role.3.economico_title": "MODELLO ECONOMICO",
    "role.3.economico_desc": "Canone di 12.000€/anno. Commissione del 30% e controllo territoriale.",
    "role.3.funciones_title": "LE TUE FUNZIONI PRINCIPALI",
    "role.3.f1": "Reclutar e formare segnalatori.",
    "role.3.f2": "Gestione strategica territoriale.",
    "role.3.f3": "Rappresentanza ufficiale del marchio.",
    "role.3.ejemplo_title": "Esempio Reale",
    "role.3.ejemplo_desc": "\"Caso Manuel: Ex direttore di banca che gestisce una provincia.\"",
    "role.4.title": "Delegato",
    "role.4.sub": "UFFICIO TECNICO",
    "role.4.desc": "Il livello più avanzato. Gestione commerciale totale e redazione di pratiche con IA.",
    "role.4.subtitle": "Controllo totale. Gestione commerciale e redazione tecnica assistita por IA.",
    "role.4.perfil_title": "PROFILO IDEALE",
    "role.4.perfil_desc": "Consulenze consolidate o esperti di R&S che cercano di massimizzare la redditività.",
    "role.4.economico_title": "MODELLO ECONOMICO",
    "role.4.economico_desc": "Modello ufficio tecnico. Massima commissione (fino al 40%).",
    "role.4.funciones_title": "LE TUE FUNZIONI PRINCIPALI",
    "role.4.f1": "Redazione tecnica con IA propria.",
    "role.4.f2": "Validazione tecnica delle pratiche.",
    "role.4.f3": "Gestione commerciale premium.",
    "role.4.ejemplo_title": "Esempio Reale",
    "role.4.ejemplo_desc": "\"Caso TechConsult: Consulenza che ha moltiplicato per 10 la sua produzione.\"",
    "portal.btn.info": "Saperne di più",
    "matcher.title": "Matcher di Carriera IA",
    "matcher.desc": "Non sai quale livello scegliere? Racconta la tua esperienza alla nostra IA.",
    "matcher.btn": "Prova Matcher IA",
    "matcher.modal.title": "Assistente Carriera",
    "matcher.modal.placeholder": "Esempio: Sono un venditore con 10 anni di esperienza in banca...",
    "matcher.modal.loading": "Analisi del profilo...",
    "matcher.modal.btn": "Analizza il mio Profilo",
    "matcher.modal.retry": "Riprova",
    "role.modal.title": "Dettagli Ruolo",
    "role.modal.close": "Capito",
    "portal.module.1": "Modulo 1: Fondamenti",
    "portal.module.2": "Modulo 2: Tecnologia",
    "portal.module.3": "Modulo 3: Commerciale",
    "portal.module.4": "Modulo 4: Pratica",
    "portal.module.1.detail": "Impara le basi del finanziamento pubblico e il modello Redescomerciales.ai.",
    "portal.module.2.detail": "Domina gli strumenti IA que ti renderanno 10 volte più produttivo.",
    "portal.module.3.detail": "Tecniche di vendita e discovery adattate agli aiuti pubblici.",
    "portal.module.4.detail": "Risoluzione di casi reali e avvio della tua attività.",
    "portal.status.locked": "Bloccato",
    "portal.status.done": "Completato",
    "portal.status.ready": "Pronto per iniziare",
    "portal.btn.start": "Inizia Modulo",
    "portal.btn.review": "Ripassa",
    "module.passed": "Modulo Superato!",
    "module.retry": "Devi ripassare",
    "module.score_msg": "Hai risposto correttamente a {score} su {total} domande.",
    "module.next": "Modulo Successivo",
    "module.repeat": "Ripeti Test",
    "module.confirm_btn": "Conferma Risposta",
    "welcome.title": "Benvenuto nel Programma",
    "welcome.desc": "Stai per iniziare una formazione che cambierà la tua carriera.",
    "welcome.warning": "Questo processo richiede impegno.",
    "welcome.btn": "Vai alla mia Dashboard",
    "admin.roles.prescriptor": "Segnalatore",
    "admin.roles.colaborador": "Collaboratore",
    "admin.roles.delegado_g": "Delegato Gestione",
    "admin.roles.oficina_t": "Ufficio Tecnico",
    "admin.stats.total": "Candidati",
    "admin.stats.pending": "In attesa",
    "admin.stats.approved": "Approvati",
    "admin.stats.interviews": "Interviste",
    "admin.overview.distribution": "Distribuzione Ruoli",
    "admin.overview.recent": "Ultimi Candidati",
    "admin.overview.pending_tasks": "Compiti Urgenti",
    "admin.overview.review_desc": "Hai {count} CV in attesa di validazione.",
    "admin.overview.next_interviews": "Prossimi Appuntamenti",
    "admin.nav.overview": "Sommario",
    "admin.nav.candidates": "Candidati",
    "admin.nav.interviews": "Calendario",
    "admin.nav.settings": "Impostazioni",
    "admin.search.placeholder": "Cerca per nome o e-mail...",
    "admin.table.candidate": "Candidato",
    "admin.table.role": "Ruolo",
    "admin.table.status": "Stato",
    "admin.table.progress": "Progresso",
    "admin.table.actions": "Azioni",
    "admin.status.review_cv": "Revisiona CV",
    "admin.status.training": "In formazione",
    "admin.btn.manage": "Gestisci",
    "admin.btn.schedule_new": "Pianifica",
    "admin.calendar.title": "Calendario Interviste",
    "admin.calendar.appointments": "Appuntamenti oggi",
    "admin.calendar.empty": "Nessun appuntamento",
    "admin.modal.approve": "Approva Candidato",
    "admin.modal.discard": "Scarta",
    "admin.modal.schedule_title": "Pianifica Intervista",
    "admin.modal.choose": "Seleziona...",
    "admin.modal.date": "Data",
    "admin.modal.time": "Ora",
    "admin.modal.save": "Salva",
    "admin.modal.saving": "Salvataggio...",
    "admin.modal.cancel": "Annulla",
    "admin.settings.tech_params": "Parametri Tecnici",
    "admin.settings.cutoff": "Punteggio Minimo",
    "admin.settings.maintenance": "Modalità Manutenzione",
    "admin.settings.maintenance_desc": "Blocca l'accesso ai candidati.",
    "admin.settings.sim_guests": "Simulazione Ospiti"
  }
};

const SettingsContext = createContext<SettingsContextType | undefined>(undefined);

export const SettingsProvider = ({ children }: { children?: ReactNode }) => {
  const [lang, setLangState] = useState<Language>(() => (localStorage.getItem('gw_lang') as Language) || 'es');
  const [theme, setThemeState] = useState<Theme>(() => (localStorage.getItem('gw_theme') as Theme) || 'light');

  useEffect(() => {
    localStorage.setItem('gw_lang', lang);
  }, [lang]);

  useEffect(() => {
    localStorage.setItem('gw_theme', theme);
    if (theme === 'dark') {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  }, [theme]);

  const toggleTheme = () => setThemeState(prev => prev === 'light' ? 'dark' : 'light');
  const setLang = (l: Language) => setLangState(l);
  
  const t = (key: string) => translations[lang][key] || translations['es'][key] || key;

  return (
    <SettingsContext.Provider value={{ lang, theme, setLang, toggleTheme, t }}>
      {children}
    </SettingsContext.Provider>
  );
};

export const useSettings = () => {
  const context = useContext(SettingsContext);
  if (!context) throw new Error('useSettings must be used within SettingsProvider');
  return context;
};
